repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format Rust source files with cargo fmt
        language: system
        entry: cargo fmt --
        types_or: [rust]
        pass_filenames: false

      - id: ruff-format
        name: ruff format
        description: Format Python source files with ruff
        language: system
        entry: ruff format
        types: [python]
