"""``data/confusables_vision.tsv`` (#738): measured-visual rows admitted by multi-font agreement.

The rows are generated by ``scripts/measure_confusable_vision.py`` from the two published
confusable-vision discovery sets, under a stated rule. This file pins the rule's constants
to the header, the rows to the fold, and the exclusions the rule makes on purpose.
"""

from __future__ import annotations

import importlib.util
import re
from pathlib import Path

import pytest

import disarm

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "confusables_vision.tsv"


def _rows() -> list[tuple[str, str, float, int]]:
    out = []
    for line in DATA.read_text(encoding="utf-8").splitlines():
        if not line or line.lstrip().startswith("#"):
            continue
        cp, latin, _cyr, ssim, fonts, _note = line.split("\t")
        out.append((chr(int(cp, 16)), latin, float(ssim), int(fonts)))
    return out


def _script_constants() -> tuple[int, float]:
    spec = importlib.util.spec_from_file_location(
        "mcv", ROOT / "scripts" / "measure_confusable_vision.py"
    )
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod.MIN_FONTS, mod.MIN_SSIM


ROWS = _rows()


def test_the_file_has_the_rows_the_rule_admits() -> None:
    assert [(r[0], r[1]) for r in ROWS] == [("〡", "l"), ("丨", "l")]


@pytest.mark.parametrize(
    ("source", "target", "ssim", "fonts"), ROWS, ids=[f"U+{ord(r[0]):04X}" for r in ROWS]
)
def test_each_row_folds_on_both_surfaces_and_is_a_fixed_point(
    source: str, target: str, ssim: float, fonts: int
) -> None:
    assert disarm.normalize_confusables(source) == target
    assert disarm.canonicalize(source) == target
    assert disarm.normalize_confusables(target) == target


@pytest.mark.parametrize(
    ("source", "target", "ssim", "fonts"), ROWS, ids=[f"U+{ord(r[0]):04X}" for r in ROWS]
)
def test_each_row_meets_the_rule_the_header_states(
    source: str, target: str, ssim: float, fonts: int
) -> None:
    min_fonts, min_ssim = _script_constants()
    assert fonts >= min_fonts and ssim >= min_ssim, (source, ssim, fonts)
    header = DATA.read_text(encoding="utf-8")
    assert f"validFontCount >= {min_fonts}" in header and f"meanSsim >= {min_ssim}" in header


@pytest.mark.parametrize(
    ("source", "why"),
    [
        ("ḷ", "an accented l (dot below) agreeing in 57 fonts is a letter, not a confusable"),
        ("꠰", "a numeric symbol agreeing in 9 fonts is what digit_policy exists to refuse"),
        ("丄", "nine fonts but SSIM 0.80, below the rule's 0.85"),
        ("ᶈ", "SSIM 0.842 in 13 fonts, below the rule's 0.85"),
    ],
)
def test_what_the_rule_leaves_out_stays_unfolded(source: str, why: str) -> None:
    # Both halves: the exclusions are decisions, and the fold still leaves them alone.
    assert disarm.canonicalize(source) == source, why


def test_the_two_headline_pairs_are_outside_the_exposure_denominator() -> None:
    # #738's structural note: `unmapped_confusables()` enumerates TR39's sources, so a
    # pair upstream never listed is outside it — and now folded anyway.
    unmapped = disarm.unmapped_confusables()
    assert "丨" not in unmapped and "〡" not in unmapped


def test_the_header_pins_its_sources_by_checksum() -> None:
    header = DATA.read_text(encoding="utf-8")
    assert len(re.findall(r"sha256 [0-9a-f]{64}", header)) == 2
