"""#481: the build-time tables stay in sync with Unicode canonical-decomposition data.

`build.rs` has no Unicode data, so the excluded-composition map and the canonical
singleton list are generated by ``scripts/gen_excluded_compositions.py`` from the
running Python's ``unicodedata`` and committed as TSVs. This test re-runs that
classification and asserts the committed files are *complete*: a future Unicode version
that adds a mapped excluded composition or a canonical singleton must not silently leave
the table behind. (The committed data is generated under a Unicode version >= the test
interpreter's, so the committed set is a superset — we assert containment, not equality.)
"""

from __future__ import annotations

import functools
import importlib.util
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DATA = REPO / "src" / "tables" / "data"

# Import the generator module directly (it lives in scripts/, not on the path).
_spec = importlib.util.spec_from_file_location(
    "gen_excluded_compositions", REPO / "scripts" / "gen_excluded_compositions.py"
)
assert _spec and _spec.loader
gen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gen)

# `classify()` does a full Unicode scan; memoize so the two tests below share one pass
# instead of scanning twice (Copilot review on #482).
_classify = functools.lru_cache(maxsize=None)(gen.classify)


def _read_excluded() -> dict[str, int]:
    out: dict[str, int] = {}
    for line in (DATA / "excluded_compositions.tsv").read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        key_hex, val_hex = line.split("\t")
        key = "".join(chr(int(h, 16)) for h in key_hex.split())
        out[key] = int(val_hex, 16)
    return out


def _read_singletons() -> dict[int, int]:
    out: dict[int, int] = {}
    for line in (DATA / "canonical_singletons.tsv").read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        s, g = line.split("\t")
        out[int(s, 16)] = int(g, 16)
    return out


def test_excluded_composition_map_is_complete() -> None:
    """Every mapped base+mark exclusion the current Unicode data yields is committed."""
    _singletons, excluded = _classify()
    committed = _read_excluded()
    missing = [(nfd, cp) for nfd, cp in excluded if committed.get(nfd) != cp]
    assert not missing, f"excluded_compositions.tsv missing entries: {missing[:10]}"


def test_canonical_singletons_are_complete() -> None:
    """Every canonical singleton the current Unicode data yields is committed."""
    singletons, _excluded = _classify()
    committed = _read_singletons()
    missing = [(s, g) for s, g in singletons if committed.get(s) != g]
    assert not missing, f"canonical_singletons.tsv missing entries: {missing[:10]}"


def test_representative_entries_present_and_cycle_cases_gated() -> None:
    """Pin the headline data: the script-letter exclusions are present, and the unmapped
    cycle case (FORKING U+2ADC) is gated out so it cannot recompose into the NFKC loop."""
    excluded = _read_excluded()
    # keys are the decomposed clusters; build them from explicit code points
    assert excluded.get("\u0915\u093c") == 0x0958, "KA+nukta -> QA missing"
    assert excluded.get("\u05e9\u05c2") == 0xFB2B, "shin+sin-dot -> U+FB2B missing"
    assert excluded.get("\u0f71\u0f72") == 0x0F73, "Tibetan vowel II missing"
    assert "\u2add\u0338" not in excluded, "unmapped FORKING U+2ADC must be gated out"

    singletons = _read_singletons()
    assert singletons.get(0x1F77) == 0x03AF, "Greek iota-oxia singleton missing"
    assert singletons.get(0x1F79) == 0x03CC, "Greek omicron-oxia singleton missing"
