//! The 128-byte ASCII slice of the Latin confusable map, in its own module (#695).
//!
//! Separated from [`super::confusables_data`] for a linker reason rather than a tidiness
//! one. That module `include!`s the generated PHF maps — roughly 550 KB of static data —
//! and this array alongside them, so the two share a codegen unit. The preset fast-path
//! guard calls [`super::is_ascii_confusable_latin`] on **every** run, which referenced
//! this array, which retained the whole unit: `strip_format` linked the Hanzi pinyin and
//! CLDR emoji tables through a 128-byte lookup it needed and nothing else it did not.
//!
//! Measured: 663 KB with the array in the shared module, 17 KB with it here.
//!
//! Still generated by build.rs from the same TSV as the map it summarises, so it cannot
//! drift from it — `tests/test_ascii_confusable_slice.rs` asserts the two agree.

// ASCII codepoints the latin map rewrites (preset fast-path guard, #458).
include!(concat!(env!("OUT_DIR"), "/ascii_confusable_latin.rs"));
