//! `EMOJI_CANDIDATE`: the BMP characters at which `src/emoji.rs`'s scanners can do
//! anything but copy the character through.
//!
//! A scanner reaching a character outside it copies it, so the bitmap must cover every
//! character the scanner's own tests would act on: a single-character name
//! (`emoji_single.tsv`), the first character of a named sequence (`emoji_starters.tsv`),
//! a character that opens an emoji presentation sequence (`emoji_presentation.tsv`), and
//! the two variation selectors and the joiner the scanners skip. The rest of what they
//! test for (regional indicators, tags) is astral, and astral characters always take the
//! full path. `emoji::tests::candidate_bitmap_covers_the_scanners` holds the bitmap equal
//! to those tests over the whole BMP.

use std::fs;
use std::path::Path;

use super::bitmap::emit_bmp_bitmap;
use super::readers::{read_char_set_tsv, read_char_str_tsv, read_range_tsv};

pub(crate) fn generate(data_dir: &Path, out_dir: &Path) {
    let single = read_char_str_tsv(&data_dir.join("emoji_single.tsv"));
    let starters = read_char_set_tsv(&data_dir.join("emoji_starters.tsv"));
    let presentation = read_range_tsv(&data_dir.join("emoji_presentation.tsv"));
    let mut code = String::from(
        "// Generated by build.rs (codegen/emoji_candidate.rs) from the emoji TSVs.\n",
    );
    emit_bmp_bitmap(
        &mut code,
        "EMOJI_CANDIDATE",
        "a demojize scanner may do more at U+{cp} than copy it",
        |c| {
            let cp = u32::from(c);
            matches!(cp, 0xFE0E | 0xFE0F | 0x200D)
                || single.contains_key(&cp)
                || starters.contains(&cp)
                || presentation.iter().any(|&(lo, hi)| (lo..=hi).contains(&cp))
        },
    );
    fs::write(out_dir.join("emoji_candidate.rs"), code).unwrap();
}
