//! The romanization of every precomposed Hangul syllable, emitted as one static string
//! and an offset array, so `tables::lookup_hangul_static` reads a table the build made
//! instead of building it on the first call.
//!
//! `hangul::romanize_hangul` is `src/tables/hangul.rs`'s own function, compiled into the
//! build script as well as the library, so the two cannot disagree; the test
//! `tables::tests::packed_hangul_matches_romanize_hangul` holds the table to it at runtime too.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use super::hangul::romanize_hangul;

/// Precomposed Hangul syllables, U+AC00..=U+D7A3.
const SYLLABLES: u32 = 11_172;

pub(crate) fn generate(out_dir: &Path) {
    let mut blob = String::new();
    let mut offsets = vec![0u32];
    for i in 0..SYLLABLES {
        let ch = char::from_u32(0xAC00 + i).expect("every Hangul syllable is a scalar");
        let romanized = romanize_hangul(ch).expect("every precomposed syllable romanizes");
        assert!(
            romanized.is_ascii(),
            "U+{:04X} romanizes to non-ASCII",
            0xAC00 + i
        );
        blob.push_str(&romanized);
        offsets.push(u32::try_from(blob.len()).expect("the blob fits in u32"));
    }
    let mut code = String::from(
        "// Generated by build.rs (codegen/hangul_table.rs) from src/tables/hangul.rs.\n",
    );
    writeln!(
        code,
        "/// Every precomposed syllable's romanization, in code point order.\n\
         static HANGUL_BLOB: &str = {blob:?};"
    )
    .unwrap();
    writeln!(
        code,
        "/// Syllable `i`'s romanization is `HANGUL_BLOB[OFFSETS[i]..OFFSETS[i + 1]]`.\n\
         static HANGUL_OFFSETS: [u32; {}] = [",
        offsets.len()
    )
    .unwrap();
    for chunk in offsets.chunks(16) {
        let row: Vec<String> = chunk.iter().map(u32::to_string).collect();
        writeln!(code, "    {},", row.join(", ")).unwrap();
    }
    code.push_str("];\n");
    fs::write(out_dir.join("hangul_table.rs"), code).unwrap();
}
