//! The normalization-boundary bitmaps `src/normalize.rs` reads to decide, per character,
//! whether the normalizer has to run at all.
//!
//! One bit per BMP code point per form: set when a boundary sits before the character
//! (a starter that passes the form's quick check). The rule is stated once more in
//! `src/normalize.rs::is_boundary_lookup`, which answers for the astral planes, and
//! `normalize::tests::boundary_bitmaps_match_the_lookup` holds the two equal over the
//! whole BMP, so a build-time copy of `unicode-normalization` that disagreed with the
//! runtime one would fail there.
//!
//! `NFD_PLAIN` marks the characters the mark walks in `src/zalgo.rs` can step over: their
//! own NFD, and not a combining mark, so each one ends whatever base came before it. The
//! same test holds it equal to `normalize::is_nfd_plain_lookup`.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use unicode_normalization::char::{canonical_combining_class, is_combining_mark};
use unicode_normalization::IsNormalized;
use unicode_normalization::{is_nfc_quick, is_nfd_quick, is_nfkc_quick, is_nfkd_quick};

const FORMS: [&str; 4] = ["NFC", "NFD", "NFKC", "NFKD"];

fn is_boundary(c: char, form: &str) -> bool {
    if canonical_combining_class(c) != 0 {
        return false;
    }
    let one = std::iter::once(c);
    let quick = match form {
        "NFC" => is_nfc_quick(one),
        "NFD" => is_nfd_quick(one),
        "NFKC" => is_nfkc_quick(one),
        "NFKD" => is_nfkd_quick(one),
        _ => unreachable!("a form outside FORMS"),
    };
    quick == IsNormalized::Yes
}

/// Emit `<FORM>_BOUNDARY: [u64; 1024]` for each form, and `NFD_PLAIN`, into
/// `norm_boundary.rs`.
pub(crate) fn generate(out_dir: &Path) {
    let mut code = String::from(
        "// Generated by build.rs (codegen/norm_boundary.rs) from `unicode-normalization`.\n",
    );
    for form in FORMS {
        emit(
            &mut code,
            &format!("{form}_BOUNDARY"),
            &format!("a normalization boundary sits before U+{{cp}} under {form}"),
            |c| is_boundary(c, form),
        );
    }
    emit(
        &mut code,
        "NFD_PLAIN",
        "U+{cp} is its own NFD and not a combining mark",
        |c| is_boundary(c, "NFD") && !is_combining_mark(c),
    );
    fs::write(out_dir.join("norm_boundary.rs"), code).unwrap();
}

fn emit(code: &mut String, name: &str, meaning: &str, set: impl Fn(char) -> bool) {
    let mut words = [0u64; 1024];
    for cp in 0..0x1_0000u32 {
        if let Some(c) = char::from_u32(cp) {
            if set(c) {
                words[(cp >> 6) as usize] |= 1 << (cp & 63);
            }
        }
    }
    writeln!(
        code,
        "/// Bit `cp` set: {meaning}.\nstatic {name}: [u64; 1024] = ["
    )
    .unwrap();
    for chunk in words.chunks(4) {
        // Grouped by 16 bits: clippy's `unreadable_literal` reads the generated file.
        let row: Vec<String> = chunk
            .iter()
            .map(|w| {
                format!(
                    "0x{:04X}_{:04X}_{:04X}_{:04X}",
                    w >> 48,
                    (w >> 32) & 0xFFFF,
                    (w >> 16) & 0xFFFF,
                    w & 0xFFFF
                )
            })
            .collect();
        writeln!(code, "    {},", row.join(", ")).unwrap();
    }
    code.push_str("];\n");
}
