/-! GENERATED by scripts/gen_tables.py from src/tables/data/*.tsv — do not edit.

The real tables, projected onto the model's alphabet plus ASCII (the character
set of every emoji name). Every predicate is `false` / `none` outside that domain;
no input or output of the model leaves it. -/

namespace Emoji.Tables

/-- U+1F600: Emoji_Presentation, named single, not a multi starter (grinning face) -/
def cE : Char := Char.ofNat 0x1F600
/-- U+1F468: Emoji_Presentation, named, multi starter: skin tone + ZWJ sequences (man) -/
def cM : Char := Char.ofNat 0x1F468
/-- U+1F525: Emoji_Presentation, named, inside a named ZWJ sequence (fire) -/
def cF : Char := Char.ofNat 0x1F525
/-- U+2764: Emoji=Yes text-default, named, multi starter (red heart) -/
def cH : Char := Char.ofNat 0x2764
/-- U+2122: Emoji=Yes text-default, named single (trade mark) -/
def cTM : Char := Char.ofNat 0x2122
/-- U+00A9: Emoji=Yes text-default, NO CLDR name (copyright) -/
def cC : Char := Char.ofNat 0xA9
/-- U+0031: keycap base, alphanumeric ('1') -/
def c1 : Char := Char.ofNat 0x31
/-- U+002A: keycap base, not alphanumeric ('*') -/
def cStar : Char := Char.ofNat 0x2A
/-- U+20E3: COMBINING ENCLOSING KEYCAP -/
def cKC : Char := Char.ofNat 0x20E3
/-- U+FE0E: VS15 -/
def cV15 : Char := Char.ofNat 0xFE0E
/-- U+FE0F: VS16 -/
def cV16 : Char := Char.ofNat 0xFE0F
/-- U+200D: ZWJ -/
def cZ : Char := Char.ofNat 0x200D
/-- U+1F3FB: skin tone (Emoji_Presentation, named alone) -/
def cT : Char := Char.ofNat 0x1F3FB
/-- U+E0041: TAG character (lone: unnamed) -/
def cG : Char := Char.ofNat 0xE0041
/-- U+1F1E6: regional indicator A -/
def cRA : Char := Char.ofNat 0x1F1E6
/-- U+1F1E7: regional indicator B -/
def cRB : Char := Char.ofNat 0x1F1E7
/-- U+0301: combining acute (Mn) -/
def cMK : Char := Char.ofNat 0x301
/-- U+0078: letter 'x' (alphanumeric; occurs in no name in the table) -/
def cX : Char := Char.ofNat 0x78
/-- U+0020: space -/
def cSP : Char := Char.ofNat 0x20
/-- U+20AC: euro: CLDR-named, no emoji property (#757 row), folds to 'e' -/
def cEU : Char := Char.ofNat 0x20AC
/-- U+002E: '.', other -/
def cDot : Char := Char.ofNat 0x2E

/-- The model's input alphabet, one code point per class the Rust branches on. -/
def alphabet : List Char := [cE, cM, cF, cH, cTM, cC, c1, cStar, cKC, cV15, cV16, cZ, cT, cG, cRA, cRB, cMK, cX, cSP, cEU, cDot]

/-- `tables::max_emoji_seq_len()` = MAX_WINDOW. -/
def maxWindow : Nat := 9

/-- UCD Emoji_Presentation=Yes (tables::is_emoji_presentation) -/
def isEmojiPresentation (c : Char) : Bool :=
  let n := c.toNat
  n == 0x1F1E6 || n == 0x1F1E7 || n == 0x1F3FB || n == 0x1F468 || n == 0x1F525 || n == 0x1F600

/-- UCD Emoji or Extended_Pictographic (tables::is_emoji_property) -/
def isEmojiProperty (c : Char) : Bool :=
  let n := c.toNat
  n == 0x23 || n == 0x2A || n == 0x30 || n == 0x31 || n == 0x32 || n == 0x33 || n == 0x34 || n == 0x35 || n == 0x36 || n == 0x37 || n == 0x38 || n == 0x39 || n == 0xA9 || n == 0x2122 || n == 0x2764 || n == 0x1F1E6 || n == 0x1F1E7 || n == 0x1F3FB || n == 0x1F468 || n == 0x1F525 || n == 0x1F600

/-- emoji_starters.tsv (tables::is_emoji_multi_starter) -/
def isStarter (c : Char) : Bool :=
  let n := c.toNat
  n == 0x23 || n == 0x2A || n == 0x30 || n == 0x31 || n == 0x32 || n == 0x33 || n == 0x34 || n == 0x35 || n == 0x36 || n == 0x37 || n == 0x38 || n == 0x39 || n == 0x2764 || n == 0x1F1E6 || n == 0x1F1E7 || n == 0x1F468

/-- CLDR row with no emoji property (tables::is_non_emoji_cldr_row, #757) -/
def nonEmojiRow (c : Char) : Bool :=
  let n := c.toNat
  n == 0x20AC

/-- lookup_confusable(c, "latin") starts with an alphanumeric -/
def confFoldsAlnum (c : Char) : Bool :=
  let n := c.toNat
  n == 0x7C || n == 0x20AC

/-- General_Category=Mark (unicode_normalization::char::is_combining_mark) -/
def isCombiningMark (c : Char) : Bool :=
  let n := c.toNat
  n == 0x301 || n == 0x20E3 || n == 0xFE0E || n == 0xFE0F

/-- char::is_alphanumeric -/
def isAlphanumeric (c : Char) : Bool :=
  let n := c.toNat
  n == 0x30 || n == 0x31 || n == 0x32 || n == 0x33 || n == 0x34 || n == 0x35 || n == 0x36 || n == 0x37 || n == 0x38 || n == 0x39 || n == 0x41 || n == 0x42 || n == 0x43 || n == 0x44 || n == 0x45 || n == 0x46 || n == 0x47 || n == 0x48 || n == 0x49 || n == 0x4A || n == 0x4B || n == 0x4C || n == 0x4D || n == 0x4E || n == 0x4F || n == 0x50 || n == 0x51 || n == 0x52 || n == 0x53 || n == 0x54 || n == 0x55 || n == 0x56 || n == 0x57 || n == 0x58 || n == 0x59 || n == 0x5A || n == 0x61 || n == 0x62 || n == 0x63 || n == 0x64 || n == 0x65 || n == 0x66 || n == 0x67 || n == 0x68 || n == 0x69 || n == 0x6A || n == 0x6B || n == 0x6C || n == 0x6D || n == 0x6E || n == 0x6F || n == 0x70 || n == 0x71 || n == 0x72 || n == 0x73 || n == 0x74 || n == 0x75 || n == 0x76 || n == 0x77 || n == 0x78 || n == 0x79 || n == 0x7A

/-- char::is_whitespace -/
def isWhitespace (c : Char) : Bool :=
  let n := c.toNat
  n == 0x9 || n == 0xA || n == 0xB || n == 0xC || n == 0xD || n == 0x1C || n == 0x1D || n == 0x1E || n == 0x1F || n == 0x20

/-- emoji_single.tsv (tables::lookup_emoji_single) -/
def single (c : Char) : Option String :=
  let n := c.toNat
  if n == 0x20AC then some "euro" else
  if n == 0x2122 then some "trade mark" else
  if n == 0x2764 then some "red heart" else
  if n == 0x1F3FB then some "light skin tone" else
  if n == 0x1F468 then some "man" else
  if n == 0x1F525 then some "fire" else
  if n == 0x1F600 then some "grinning face" else
  none

/-- emoji_multi.tsv keys over the alphabet (the trie `match_emoji_sequence` walks). -/
def multiKeys : List (List Char × String) := [
  ([Char.ofNat 0x2A, Char.ofNat 0x20E3], "keycap: *"),
  ([Char.ofNat 0x31, Char.ofNat 0x20E3], "keycap: 1"),
  ([Char.ofNat 0x2764, Char.ofNat 0x200D, Char.ofNat 0x1F525], "heart on fire"),
  ([Char.ofNat 0x1F1E7, Char.ofNat 0x1F1E6], "flag: Bosnia & Herzegovina"),
  ([Char.ofNat 0x1F1E7, Char.ofNat 0x1F1E7], "flag: Barbados"),
  ([Char.ofNat 0x1F468, Char.ofNat 0x200D, Char.ofNat 0x2764, Char.ofNat 0x200D, Char.ofNat 0x1F468], "couple with heart: man, man"),
  ([Char.ofNat 0x1F468, Char.ofNat 0x1F3FB], "man: light skin tone"),
  ([Char.ofNat 0x1F468, Char.ofNat 0x1F3FB, Char.ofNat 0x200D, Char.ofNat 0x2764, Char.ofNat 0x200D, Char.ofNat 0x1F468, Char.ofNat 0x1F3FB], "couple with heart: man, man, light skin tone")
]

end Emoji.Tables
