/-! GENERATED by scripts/gen_tables.py from src/tables/data/*.tsv and the built
library. Do not edit by hand. See that script's docstring for provenance. -/

namespace Confusables.Tables

/-- 'a': plain ASCII letter, the target of U+0430 -/
def cA : Char := '\u0061'
/-- 'C': uppercase ASCII (fold_case, guard), target of U+04AA -/
def cCu : Char := '\u0043'
/-- 'y': composes with U+0300 to U+1EF3, a fold source -/
def cY : Char := '\u0079'
/-- 'I': the prototype fold's letter half (I -> l) -/
def cI : Char := '\u0049'
/-- '1': the prototype fold's digit half under tr39 -/
def c1 : Char := '\u0031'
/-- '|': an ASCII fold source that detection skips (#957) -/
def cBar : Char := '\u007C'
/-- space: collapse_whitespace, the guard's WhitespaceOnly verdict -/
def cSp : Char := '\u0020'
/-- U+0001: a control StripControl removes -/
def cCtl : Char := '\u0001'
/-- CYRILLIC SMALL A: the basic homoglyph, folds to 'a' -/
def cCyrA : Char := '\u0430'
/-- YEN SIGN: folds to 'Y', which then composes with a mark (#522) -/
def cYen : Char := '\u00A5'
/-- CYRILLIC CAPITAL ES WITH DESCENDER: folds to 'C'; + U+0327 composes to a source -/
def cCyrS : Char := '\u04AA'
/-- COMBINING GRAVE (Mn, ccc 230) -/
def cGrave : Char := '\u0300'
/-- COMBINING CEDILLA (Mn, ccc 202) -/
def cCed : Char := '\u0327'
/-- COMBINING DIAERESIS (Mn, ccc 230) -/
def cDia : Char := '\u0308'
/-- COMBINING ACUTE (Mn, ccc 230) -/
def cAcute : Char := '\u0301'
/-- GREEK SMALL IOTA WITH DIALYTIKA AND TONOS: case-folds to a decomposed triple -/
def cIota3 : Char := '\u0390'
/-- y WITH GRAVE: folds to a NON-ASCII value (U+00FD) -/
def cYGr : Char := '\u1EF3'
/-- DEVANAGARI ZERO: a digit row (numeric 0, tr39 o, preserve keeps) -/
def cDev0 : Char := '\u0966'
/-- KIRAT RAI VOWEL SIGN E: a starter that composes with a starter (Unicode 16) -/
def cKr : Char := (Char.ofNat 0x16D67)
/-- OHM SIGN: an NFC singleton, only foldable after NFKC + case fold -/
def cOhm : Char := '\u2126'
/-- a WITH MACRON: folds to a NON-ASCII value (U+00E3) -/
def cAMac : Char := '\u0101'

/-- The input alphabet: one representative per class the Rust code branches on. -/
def alphabet : List Char := [cA, cCu, cY, cI, c1, cBar, cSp, cCtl, cCyrA, cYen, cCyrS, cGrave, cCed, cDia, cAcute, cIota3, cYGr, cDev0, cKr, cOhm, cAMac]

/-- The closed domain (94 code points). -/
def domain : List Char := ['\u0001', '\u0020', '\u0030', '\u0031', '\u0043', '\u0049', '\u0059', '\u0061', '\u0063', '\u0069', '\u006C', '\u006F', '\u0077', '\u0079', '\u007C', '\u00A5', '\u00C7', '\u00CC', '\u00CD', '\u00CF', '\u00DD', '\u00E0', '\u00E1', '\u00E3', '\u00E4', '\u00E7', '\u00EC', '\u00ED', '\u00EF', '\u00F2', '\u00F3', '\u00F5', '\u00F6', '\u00FD', '\u00FF', '\u0101', '\u0106', '\u0107', '\u0128', '\u0129', '\u012A', '\u012B', '\u013A', '\u013C', '\u014D', '\u0178', '\u01DF', '\u022B', '\u022D', '\u0232', '\u0233', '\u0300', '\u0301', '\u0303', '\u0304', '\u0308', '\u0327', '\u0344', '\u038F', '\u0390', '\u03A9', '\u03AF', '\u03B9', '\u03C9', '\u03CA', '\u03CE', '\u0430', '\u04AA', '\u04AB', '\u04D3', '\u0966', '\u1E08', '\u1E09', '\u1E2E', '\u1E2F', '\u1E4D', '\u1E4F', '\u1E51', '\u1E53', '\u1E81', '\u1E83', '\u1E85', '\u1EF2', '\u1EF3', '\u1EF8', '\u1EF9', '\u1F76', '\u1F7C', '\u1FD1', '\u1FD2', '\u1FFA', '\u2126', (Char.ofNat 0x16D67), (Char.ofNat 0x16D68)]

/-- Canonical_Combining_Class. -/
def ccc (c : Char) : Nat :=
  match c.toNat with
  | 0x300 => 230
  | 0x301 => 230
  | 0x303 => 230
  | 0x304 => 230
  | 0x308 => 230
  | 0x327 => 202
  | 0x344 => 230
  | _ => 0

/-- General_Category = Mark (`unicode_normalization::char::is_combining_mark`). -/
def isMark (c : Char) : Bool :=
  let n := c.toNat
  n == 0x300 || n == 0x301 || n == 0x303 || n == 0x304 || n == 0x308 || n == 0x327 || n == 0x344

/-- Full canonical decomposition of one code point (library NFD). -/
def canonDecomp (c : Char) : List Char :=
  match c.toNat with
  | 0xC7 => ['\u0043', '\u0327']
  | 0xCC => ['\u0049', '\u0300']
  | 0xCD => ['\u0049', '\u0301']
  | 0xCF => ['\u0049', '\u0308']
  | 0xDD => ['\u0059', '\u0301']
  | 0xE0 => ['\u0061', '\u0300']
  | 0xE1 => ['\u0061', '\u0301']
  | 0xE3 => ['\u0061', '\u0303']
  | 0xE4 => ['\u0061', '\u0308']
  | 0xE7 => ['\u0063', '\u0327']
  | 0xEC => ['\u0069', '\u0300']
  | 0xED => ['\u0069', '\u0301']
  | 0xEF => ['\u0069', '\u0308']
  | 0xF2 => ['\u006F', '\u0300']
  | 0xF3 => ['\u006F', '\u0301']
  | 0xF5 => ['\u006F', '\u0303']
  | 0xF6 => ['\u006F', '\u0308']
  | 0xFD => ['\u0079', '\u0301']
  | 0xFF => ['\u0079', '\u0308']
  | 0x101 => ['\u0061', '\u0304']
  | 0x106 => ['\u0043', '\u0301']
  | 0x107 => ['\u0063', '\u0301']
  | 0x128 => ['\u0049', '\u0303']
  | 0x129 => ['\u0069', '\u0303']
  | 0x12A => ['\u0049', '\u0304']
  | 0x12B => ['\u0069', '\u0304']
  | 0x13A => ['\u006C', '\u0301']
  | 0x13C => ['\u006C', '\u0327']
  | 0x14D => ['\u006F', '\u0304']
  | 0x178 => ['\u0059', '\u0308']
  | 0x1DF => ['\u0061', '\u0308', '\u0304']
  | 0x22B => ['\u006F', '\u0308', '\u0304']
  | 0x22D => ['\u006F', '\u0303', '\u0304']
  | 0x232 => ['\u0059', '\u0304']
  | 0x233 => ['\u0079', '\u0304']
  | 0x344 => ['\u0308', '\u0301']
  | 0x38F => ['\u03A9', '\u0301']
  | 0x390 => ['\u03B9', '\u0308', '\u0301']
  | 0x3AF => ['\u03B9', '\u0301']
  | 0x3CA => ['\u03B9', '\u0308']
  | 0x3CE => ['\u03C9', '\u0301']
  | 0x4D3 => ['\u0430', '\u0308']
  | 0x1E08 => ['\u0043', '\u0327', '\u0301']
  | 0x1E09 => ['\u0063', '\u0327', '\u0301']
  | 0x1E2E => ['\u0049', '\u0308', '\u0301']
  | 0x1E2F => ['\u0069', '\u0308', '\u0301']
  | 0x1E4D => ['\u006F', '\u0303', '\u0301']
  | 0x1E4F => ['\u006F', '\u0303', '\u0308']
  | 0x1E51 => ['\u006F', '\u0304', '\u0300']
  | 0x1E53 => ['\u006F', '\u0304', '\u0301']
  | 0x1E81 => ['\u0077', '\u0300']
  | 0x1E83 => ['\u0077', '\u0301']
  | 0x1E85 => ['\u0077', '\u0308']
  | 0x1EF2 => ['\u0059', '\u0300']
  | 0x1EF3 => ['\u0079', '\u0300']
  | 0x1EF8 => ['\u0059', '\u0303']
  | 0x1EF9 => ['\u0079', '\u0303']
  | 0x1F76 => ['\u03B9', '\u0300']
  | 0x1F7C => ['\u03C9', '\u0300']
  | 0x1FD1 => ['\u03B9', '\u0304']
  | 0x1FD2 => ['\u03B9', '\u0308', '\u0300']
  | 0x1FFA => ['\u03A9', '\u0300']
  | 0x2126 => ['\u03A9']
  | 0x16D68 => [(Char.ofNat 0x16D67), (Char.ofNat 0x16D67)]
  | _ => [c]

/-- Full compatibility decomposition of one code point (library NFKD). -/
def compatDecomp (c : Char) : List Char :=
  match c.toNat with
  | 0xC7 => ['\u0043', '\u0327']
  | 0xCC => ['\u0049', '\u0300']
  | 0xCD => ['\u0049', '\u0301']
  | 0xCF => ['\u0049', '\u0308']
  | 0xDD => ['\u0059', '\u0301']
  | 0xE0 => ['\u0061', '\u0300']
  | 0xE1 => ['\u0061', '\u0301']
  | 0xE3 => ['\u0061', '\u0303']
  | 0xE4 => ['\u0061', '\u0308']
  | 0xE7 => ['\u0063', '\u0327']
  | 0xEC => ['\u0069', '\u0300']
  | 0xED => ['\u0069', '\u0301']
  | 0xEF => ['\u0069', '\u0308']
  | 0xF2 => ['\u006F', '\u0300']
  | 0xF3 => ['\u006F', '\u0301']
  | 0xF5 => ['\u006F', '\u0303']
  | 0xF6 => ['\u006F', '\u0308']
  | 0xFD => ['\u0079', '\u0301']
  | 0xFF => ['\u0079', '\u0308']
  | 0x101 => ['\u0061', '\u0304']
  | 0x106 => ['\u0043', '\u0301']
  | 0x107 => ['\u0063', '\u0301']
  | 0x128 => ['\u0049', '\u0303']
  | 0x129 => ['\u0069', '\u0303']
  | 0x12A => ['\u0049', '\u0304']
  | 0x12B => ['\u0069', '\u0304']
  | 0x13A => ['\u006C', '\u0301']
  | 0x13C => ['\u006C', '\u0327']
  | 0x14D => ['\u006F', '\u0304']
  | 0x178 => ['\u0059', '\u0308']
  | 0x1DF => ['\u0061', '\u0308', '\u0304']
  | 0x22B => ['\u006F', '\u0308', '\u0304']
  | 0x22D => ['\u006F', '\u0303', '\u0304']
  | 0x232 => ['\u0059', '\u0304']
  | 0x233 => ['\u0079', '\u0304']
  | 0x344 => ['\u0308', '\u0301']
  | 0x38F => ['\u03A9', '\u0301']
  | 0x390 => ['\u03B9', '\u0308', '\u0301']
  | 0x3AF => ['\u03B9', '\u0301']
  | 0x3CA => ['\u03B9', '\u0308']
  | 0x3CE => ['\u03C9', '\u0301']
  | 0x4D3 => ['\u0430', '\u0308']
  | 0x1E08 => ['\u0043', '\u0327', '\u0301']
  | 0x1E09 => ['\u0063', '\u0327', '\u0301']
  | 0x1E2E => ['\u0049', '\u0308', '\u0301']
  | 0x1E2F => ['\u0069', '\u0308', '\u0301']
  | 0x1E4D => ['\u006F', '\u0303', '\u0301']
  | 0x1E4F => ['\u006F', '\u0303', '\u0308']
  | 0x1E51 => ['\u006F', '\u0304', '\u0300']
  | 0x1E53 => ['\u006F', '\u0304', '\u0301']
  | 0x1E81 => ['\u0077', '\u0300']
  | 0x1E83 => ['\u0077', '\u0301']
  | 0x1E85 => ['\u0077', '\u0308']
  | 0x1EF2 => ['\u0059', '\u0300']
  | 0x1EF3 => ['\u0079', '\u0300']
  | 0x1EF8 => ['\u0059', '\u0303']
  | 0x1EF9 => ['\u0079', '\u0303']
  | 0x1F76 => ['\u03B9', '\u0300']
  | 0x1F7C => ['\u03C9', '\u0300']
  | 0x1FD1 => ['\u03B9', '\u0304']
  | 0x1FD2 => ['\u03B9', '\u0308', '\u0300']
  | 0x1FFA => ['\u03A9', '\u0300']
  | 0x2126 => ['\u03A9']
  | 0x16D68 => [(Char.ofNat 0x16D67), (Char.ofNat 0x16D67)]
  | _ => [c]

/-- Primary composites over the domain (composition exclusions removed). -/
def composePair (a b : Char) : Option Char :=
  match a.toNat, b.toNat with
  | 0x43, 0x301 => some '\u0106'
  | 0x43, 0x327 => some '\u00C7'
  | 0x49, 0x300 => some '\u00CC'
  | 0x49, 0x301 => some '\u00CD'
  | 0x49, 0x303 => some '\u0128'
  | 0x49, 0x304 => some '\u012A'
  | 0x49, 0x308 => some '\u00CF'
  | 0x59, 0x300 => some '\u1EF2'
  | 0x59, 0x301 => some '\u00DD'
  | 0x59, 0x303 => some '\u1EF8'
  | 0x59, 0x304 => some '\u0232'
  | 0x59, 0x308 => some '\u0178'
  | 0x61, 0x300 => some '\u00E0'
  | 0x61, 0x301 => some '\u00E1'
  | 0x61, 0x303 => some '\u00E3'
  | 0x61, 0x304 => some '\u0101'
  | 0x61, 0x308 => some '\u00E4'
  | 0x63, 0x301 => some '\u0107'
  | 0x63, 0x327 => some '\u00E7'
  | 0x69, 0x300 => some '\u00EC'
  | 0x69, 0x301 => some '\u00ED'
  | 0x69, 0x303 => some '\u0129'
  | 0x69, 0x304 => some '\u012B'
  | 0x69, 0x308 => some '\u00EF'
  | 0x6C, 0x301 => some '\u013A'
  | 0x6C, 0x327 => some '\u013C'
  | 0x6F, 0x300 => some '\u00F2'
  | 0x6F, 0x301 => some '\u00F3'
  | 0x6F, 0x303 => some '\u00F5'
  | 0x6F, 0x304 => some '\u014D'
  | 0x6F, 0x308 => some '\u00F6'
  | 0x77, 0x300 => some '\u1E81'
  | 0x77, 0x301 => some '\u1E83'
  | 0x77, 0x308 => some '\u1E85'
  | 0x79, 0x300 => some '\u1EF3'
  | 0x79, 0x301 => some '\u00FD'
  | 0x79, 0x303 => some '\u1EF9'
  | 0x79, 0x304 => some '\u0233'
  | 0x79, 0x308 => some '\u00FF'
  | 0xC7, 0x301 => some '\u1E08'
  | 0xCF, 0x301 => some '\u1E2E'
  | 0xE4, 0x304 => some '\u01DF'
  | 0xE7, 0x301 => some '\u1E09'
  | 0xEF, 0x301 => some '\u1E2F'
  | 0xF5, 0x301 => some '\u1E4D'
  | 0xF5, 0x304 => some '\u022D'
  | 0xF5, 0x308 => some '\u1E4F'
  | 0xF6, 0x304 => some '\u022B'
  | 0x14D, 0x300 => some '\u1E51'
  | 0x14D, 0x301 => some '\u1E53'
  | 0x3A9, 0x300 => some '\u1FFA'
  | 0x3A9, 0x301 => some '\u038F'
  | 0x3B9, 0x300 => some '\u1F76'
  | 0x3B9, 0x301 => some '\u03AF'
  | 0x3B9, 0x304 => some '\u1FD1'
  | 0x3B9, 0x308 => some '\u03CA'
  | 0x3C9, 0x300 => some '\u1F7C'
  | 0x3C9, 0x301 => some '\u03CE'
  | 0x3CA, 0x300 => some '\u1FD2'
  | 0x3CA, 0x301 => some '\u0390'
  | 0x430, 0x308 => some '\u04D3'
  | 0x16D67, 0x16D67 => some (Char.ofNat 0x16D68)
  | _, _ => none

/-- The #481 widening map (excluded_compositions.tsv) restricted to keys over the domain. -/
def excludedCompositions : List (Prod (List Char) Char) := [(['\u0308', '\u0301'], '\u0344')]

/-- confusables_to_latin.tsv. -/
def latinMap (c : Char) : Option (List Char) :=
  match c.toNat with
  | 0x7C => some ['\u006C']
  | 0xA5 => some ['\u0059']
  | 0xC7 => some ['\u0043']
  | 0xE7 => some ['\u0063']
  | 0x101 => some ['\u00E3']
  | 0x12B => some ['\u0129']
  | 0x14D => some ['\u00F5']
  | 0x3AF => some ['\u0069']
  | 0x3B9 => some ['\u0069']
  | 0x3C9 => some ['\u0077']
  | 0x3CA => some ['\u0069']
  | 0x430 => some ['\u0061']
  | 0x4AA => some ['\u0043']
  | 0x4AB => some ['\u0063']
  | 0x966 => some ['\u0030']
  | 0x1EF3 => some ['\u00FD']
  | _ => none

/-- confusables_digit_tr39.tsv. -/
def tr39Override (c : Char) : Option (List Char) :=
  match c.toNat with
  | 0x966 => some ['\u006F']
  | _ => none

/-- confusables_upstream_sources.tsv. -/
def upstreamSource (c : Char) : Bool :=
  let n := c.toNat
  n == 0x30 || n == 0x31 || n == 0x49 || n == 0x7C || n == 0xA5 || n == 0xC7 || n == 0xE7 || n == 0xF6 || n == 0x327 || n == 0x3B9 || n == 0x430 || n == 0x4AA || n == 0x4AB || n == 0x966 || n == 0x2126

/-- Full case folding of one code point (`fold_case`). -/
def caseFold (c : Char) : List Char :=
  match c.toNat with
  | 0x43 => ['\u0063']
  | 0x49 => ['\u0069']
  | 0x59 => ['\u0079']
  | 0xC7 => ['\u00E7']
  | 0xCC => ['\u00EC']
  | 0xCD => ['\u00ED']
  | 0xCF => ['\u00EF']
  | 0xDD => ['\u00FD']
  | 0x106 => ['\u0107']
  | 0x128 => ['\u0129']
  | 0x12A => ['\u012B']
  | 0x178 => ['\u00FF']
  | 0x232 => ['\u0233']
  | 0x38F => ['\u03CE']
  | 0x390 => ['\u03B9', '\u0308', '\u0301']
  | 0x3A9 => ['\u03C9']
  | 0x4AA => ['\u04AB']
  | 0x1E08 => ['\u1E09']
  | 0x1E2E => ['\u1E2F']
  | 0x1EF2 => ['\u1EF3']
  | 0x1EF8 => ['\u1EF9']
  | 0x1FD2 => ['\u03B9', '\u0308', '\u0300']
  | 0x1FFA => ['\u1F7C']
  | 0x2126 => ['\u03C9']
  | _ => [c]

/-- `char::is_control` (General_Category = Cc). -/
def isControl (c : Char) : Bool :=
  let n := c.toNat
  n == 0x1

/-- `whitespace::is_fold_whitespace` (+ `is_blank_render`). -/
def isFoldWs (c : Char) : Bool :=
  let n := c.toNat
  n == 0x20

/-- presets.rs `acts_on_nonascii` under skeleton_key's mask. -/
def guardNonAscii (c : Char) : Bool :=
  let n := c.toNat
  n == 0x1 || n == 0x20 || n == 0x43 || n == 0x49 || n == 0x59 || n == 0x7C || n == 0xA5 || n == 0xC7 || n == 0xCC || n == 0xCD || n == 0xCF || n == 0xDD || n == 0xE7 || n == 0x101 || n == 0x106 || n == 0x128 || n == 0x12A || n == 0x12B || n == 0x14D || n == 0x178 || n == 0x232 || n == 0x300 || n == 0x301 || n == 0x303 || n == 0x304 || n == 0x308 || n == 0x327 || n == 0x344 || n == 0x38F || n == 0x390 || n == 0x3A9 || n == 0x3AF || n == 0x3B9 || n == 0x3C9 || n == 0x3CA || n == 0x430 || n == 0x4AA || n == 0x4AB || n == 0x966 || n == 0x1E08 || n == 0x1E2E || n == 0x1EF2 || n == 0x1EF3 || n == 0x1EF8 || n == 0x1FD2 || n == 0x1FFA || n == 0x2126

end Confusables.Tables
