#!/usr/bin/env python3
"""Compile-and-run every ```rust block in the docs (#50 phase 5).

The user guide shows per-language usage in tabs; the Rust tabs use `assert_eq!`
so they are real, checkable examples rather than decorative snippets. This script
is their gate — the Rust analogue of the Sybil doc-test gate for Python:

1. Extract every ```rust fenced block from docs/ (including those indented inside
   `pymdownx.tabbed` tabs).
2. Generate a throwaway integration test (one `#[test]` per block) under tests/.
3. `cargo test` it against the pure-Rust core.

`#![deny(unused_must_use)]` is set so an example that *discards* a `#[must_use]`
return (a `Result`, a `Vec`, a `Cow`) is a hard error — that forces every example
to actually assert its output, which is what keeps the documented Rust behaviour
honest. A shared `use` preamble is injected and each block's own `use` lines are
stripped, so blocks stay copy-pasteable in the docs without colliding here.

Usage:
    python3 scripts/check_doc_rust_examples.py            # generate + cargo test
    python3 scripts/check_doc_rust_examples.py --generate # write the test only
"""

from __future__ import annotations

import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = ROOT / "tests" / "_doc_rust_examples.rs"

# Injected into every block so snippets need not repeat imports here; the blocks'
# own `use` lines are stripped to avoid duplicate-import errors.
PREAMBLE = (
    "use disarm::api::{self, Transliterate, Scheme, TargetScript, NormalizationForm, "
    "ReverseLang, SlugConfig, OnUnknown, Platform, UrlComponent};\n"
    "use disarm::DisarmStr;\n"
)

_FENCE = re.compile(r"(?m)^([ \t]*)```rust\n(.*?)\n[ \t]*```", re.DOTALL)
_USE = re.compile(r"\s*use\s+.*;")
_MAIN = re.compile(r"\s*fn main\s*\(\)\s*\{?\s*$")
# Opt-out for a block that is illustration (a trait sketch, a macro), not a
# runnable example. Deliberately NOT Sybil's `<!--- skip: next -->`: that directive
# is consumed by Sybil's Python skip state machine, and placing it before a
# (non-Python) rust block on a Sybil-executed page raises "skip: next cannot
# follow skip: next". This marker contains no `skip:` token, so Sybil ignores it.
_SKIP = "<!--- rust-skip -->"


def _unwrap(lines: list[str]) -> list[str]:
    """Drop `use` lines (a shared preamble is injected) and, only when the block
    is wrapped in `fn main() { ... }`, that wrapper. A standalone `}` is otherwise
    kept — it may close a real `if`/`match`/closure in the snippet."""
    kept = [ln for ln in lines if not _USE.match(ln)]
    if any(_MAIN.match(ln) for ln in kept):
        kept = [ln for ln in kept if not _MAIN.match(ln)]
        for i in range(len(kept) - 1, -1, -1):  # drop the matching close brace
            if kept[i].strip() == "}":
                del kept[i]
                break
    return kept


def _blocks() -> list[tuple[str, str]]:
    found: list[tuple[str, str]] = []
    for md in sorted(DOCS.rglob("*.md")):
        text = md.read_text(encoding="utf-8")
        for m in _FENCE.finditer(text):
            preceding = text[: m.start()].rstrip()
            if preceding.endswith(_SKIP):
                continue
            indent, body = m.group(1), m.group(2)
            lines = [ln[len(indent) :] if ln.startswith(indent) else ln for ln in body.split("\n")]
            found.append((md.relative_to(ROOT).as_posix(), "\n".join(_unwrap(lines))))
    return found


def _render(blocks: list[tuple[str, str]]) -> str:
    out = [
        "// AUTO-GENERATED by scripts/check_doc_rust_examples.py — do not edit or commit.",
        "#![allow(unused_variables, unused_imports, dead_code, clippy::all)]",
        "#![deny(unused_must_use)]",
    ]
    for i, (src, body) in enumerate(blocks):
        out.append(f"#[test]\nfn doc_{i}() {{ // {src}\n{PREAMBLE}\n{body}\n}}")
    return "\n\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    blocks = _blocks()
    OUT.write_text(_render(blocks), encoding="utf-8")
    print(f"generated {OUT.relative_to(ROOT)} — {len(blocks)} rust doc blocks")
    if "--generate" in argv:
        return 0
    proc = subprocess.run(
        ["cargo", "test", "--test", "_doc_rust_examples", "--no-default-features"],
        cwd=ROOT,
    )
    return proc.returncode


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
