#!/usr/bin/env python3
"""Generate src/metadata.rs from the Python curated metadata (single source port).

The language/script metadata historically lived only in the Python layer
(``python/disarm/_enums.py``: ``LANG_META``, ``SCRIPT_META``, ``Script``). To give
the Rust core — and therefore every binding — the same ``lang_info`` / ``script_info``
/ ``list_scripts`` / ``list_context_langs`` surface, that curated data is ported into
the core. `python/disarm/_enums.py` remains the authored source of truth; this
script emits `src/metadata.rs` as a generated mirror (rustfmt-canonicalized) so the
two never drift, and the bindings read the data back through the core api.

Run (with disarm importable, e.g. after ``maturin develop``):

    python scripts/gen_metadata.py        # writes src/metadata.rs

The output is committed; `tests/test_metadata_parity.py` is the hard drift guard.
"""

from __future__ import annotations

import pathlib
import subprocess
import sys

from disarm._enums import LANG_META, SCRIPT_META, Script

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "src" / "metadata.rs"


def rs_str(value: str) -> str:
    """A Rust string literal (UTF-8 is fine in Rust; escape backslash and quote)."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def rs_opt(value: str | None) -> str:
    return f"Some({rs_str(value)})" if value is not None else "None"


def main() -> None:
    lines: list[str] = [
        "//! Curated language/script metadata — the single source for `lang_info`,",
        "//! `script_info`, `list_scripts`, and `list_context_langs` across every binding.",
        "//!",
        "//! AUTO-GENERATED by `scripts/gen_metadata.py` from `python/disarm/_enums.py`.",
        "//! Do not edit by hand; regenerate with `python scripts/gen_metadata.py`.",
        "",
        "/// One language's metadata (`name`, dominant `script`, `region`, `context` level).",
        "pub(crate) struct LangRow {",
        "    pub name: &'static str,",
        "    pub script: &'static str,",
        "    pub region: &'static str,",
        '    /// Context-aware transliteration support: `"none"`, `"partial"`, or `"full"`.',
        "    pub context: &'static str,",
        "}",
        "",
        "/// One script's metadata (`name`, `default_lang`, an `example`, `context_aware`).",
        "pub(crate) struct ScriptRow {",
        "    pub name: &'static str,",
        "    pub default_lang: Option<&'static str>,",
        "    pub example: &'static str,",
        "    pub context_aware: bool,",
        "}",
        "",
        "/// `(code, row)` sorted by code — binary-searched by [`lang`].",
        "pub(crate) static LANGS: &[(&str, LangRow)] = &[",
    ]
    for code in sorted(LANG_META):
        m = LANG_META[code]
        lines.append(
            f"    ({rs_str(code)}, LangRow {{ name: {rs_str(m['name'])}, "
            f"script: {rs_str(m['script'])}, region: {rs_str(m['region'])}, "
            f"context: {rs_str(m['context'])} }}),"
        )
    lines += [
        "];",
        "",
        "/// `(name, row)` sorted by name — binary-searched by [`script`].",
        "pub(crate) static SCRIPTS_META: &[(&str, ScriptRow)] = &[",
    ]
    for name in sorted(SCRIPT_META):
        m = SCRIPT_META[name]
        lines.append(
            f"    ({rs_str(name)}, ScriptRow {{ name: {rs_str(m['name'])}, "
            f"default_lang: {rs_opt(m['default_lang'])}, example: {rs_str(m['example'])}, "
            f"context_aware: {str(m['context_aware']).lower()} }}),"
        )
    lines += [
        "];",
        "",
        "/// Every recognized script name (the `Script` enum), sorted. Includes `Common`",
        "/// and `Inherited`, which have no [`SCRIPTS_META`] entry.",
        "pub(crate) static SCRIPTS: &[&str] = &[",
    ]
    for s in sorted(v.value for v in Script):
        lines.append(f"    {rs_str(s)},")
    lines += [
        "];",
        "",
        "/// Look up a language by code (binary search).",
        "pub(crate) fn lang(code: &str) -> Option<&'static LangRow> {",
        "    LANGS.binary_search_by_key(&code, |(k, _)| *k).ok().map(|i| &LANGS[i].1)",
        "}",
        "",
        "/// Look up a script by name (binary search).",
        "pub(crate) fn script(name: &str) -> Option<&'static ScriptRow> {",
        "    SCRIPTS_META.binary_search_by_key(&name, |(k, _)| *k).ok().map(|i| &SCRIPTS_META[i].1)",
        "}",
        "",
        # C-1: `lang()`/`script()` binary-search these arrays, so they must stay
        # strictly sorted (and unique) by key. Emitted alongside the data so a
        # future out-of-order `gen_metadata.py` change is caught, mirroring
        # `builtin_langs_is_sorted` in `tables/mod.rs`.
        "#[cfg(test)]",
        "mod tests {",
        "    use super::*;",
        "",
        "    #[test]",
        "    fn langs_sorted_by_code() {",
        "        assert!(",
        "            LANGS.windows(2).all(|w| w[0].0 < w[1].0),",
        '            "LANGS must be strictly sorted by code for binary_search"',
        "        );",
        "    }",
        "",
        "    #[test]",
        "    fn scripts_meta_sorted_by_name() {",
        "        assert!(",
        "            SCRIPTS_META.windows(2).all(|w| w[0].0 < w[1].0),",
        '            "SCRIPTS_META must be strictly sorted by name for binary_search"',
        "        );",
        "    }",
        "",
        "    #[test]",
        "    fn scripts_sorted_and_unique() {",
        "        assert!(",
        "            SCRIPTS.windows(2).all(|w| w[0] < w[1]),",
        '            "SCRIPTS must be strictly sorted and unique"',
        "        );",
        "    }",
        "}",
        "",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    # Canonicalize with rustfmt (edition 2021) so the committed file matches what
    # `cargo fmt` produces and the drift guard (tests/test_metadata_parity.py)
    # compares like with like regardless of the emitter's raw line wrapping.
    fmt = subprocess.run(
        ["rustfmt", "--edition", "2021", str(OUT)],
        capture_output=True,
        text=True,
        check=False,
    )
    if fmt.returncode != 0:
        print(f"warning: rustfmt failed: {fmt.stderr.strip()}", file=sys.stderr)
    print(
        f"wrote {OUT}: {len(LANG_META)} langs, {len(SCRIPT_META)} scripts_meta, "
        f"{len(list(Script))} scripts"
    )


if __name__ == "__main__":
    main()
