#!/usr/bin/env python3
"""Generate `src/tables/data/decimal_digit_zeros.tsv` — one row per numbering system.

UTS #39 §5.3 defines a **Mixed Numbers** check: an identifier should not carry digits from
more than one decimal numbering system. `1٢۳４५` is five systems and reads as `12345`.

A decimal numbering system is a run of ten code points with `Numeric_Type=Decimal` and
values 0–9. Its identity is the code point of its **zero**, which for any digit in it is
`cp - value`. So the whole table is the list of zeros, and two digits belong to the same
system exactly when `cp - value` matches.

UCD 17.0.0 has **77** of them and every run is complete, so each row is a zero and the
system is `[zero, zero + 9]`. (UTS #39 and #777 say 76; that figure is UCD 16.0.0.)

Needs an interpreter whose `unicodedata` is the bundled UCD version — the repository's
other generators use `uv run --python 3.15` for the same reason, and CPython 3.13 ships
UCD 15.1.0, which gives a different count.

    uv run --python 3.15 python scripts/gen_decimal_digit_zeros.py
"""

from __future__ import annotations

import pathlib
import sys
import unicodedata

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "tables" / "data" / "decimal_digit_zeros.tsv"

#: The Unicode version this table is a snapshot of. Matches the other bundled tables.
DATA_UNICODE_VERSION = "17.0.0"


def digit_zeros() -> list[int]:
    """Every code point that starts a complete 0–9 decimal run."""
    runs: dict[int, set[int]] = {}
    for cp in range(0x30, 0x110000):
        try:
            value = unicodedata.decimal(chr(cp))
        except ValueError:
            continue
        runs.setdefault(cp - value, set()).add(value)
    complete = sorted(zero for zero, values in runs.items() if values == set(range(10)))
    partial = sorted(zero for zero, values in runs.items() if values != set(range(10)))
    if partial:
        # Not fatal, but it would mean the "system = zero, span = ten" model no longer
        # holds and the consumer needs changing rather than the table regenerating.
        print(
            f"warning: {len(partial)} incomplete decimal runs, first at "
            f"U+{partial[0]:04X} — the ten-wide span assumption no longer holds",
            file=sys.stderr,
        )
    return complete


def main() -> int:
    if unicodedata.unidata_version != DATA_UNICODE_VERSION:
        print(
            f"refusing to generate: this interpreter has UCD "
            f"{unicodedata.unidata_version}, the bundled tables are "
            f"{DATA_UNICODE_VERSION}. Use `uv run --python 3.15`.",
            file=sys.stderr,
        )
        return 2

    zeros = digit_zeros()
    lines = [
        f"# Decimal numbering systems — UCD {DATA_UNICODE_VERSION} Numeric_Type=Decimal.",
        "# One row per system: the code point of its ZERO. The system spans ten code",
        "# points, so a digit belongs to it when `cp - decimal_value` equals this.",
        "# Generated by scripts/gen_decimal_digit_zeros.py — see docs/provenance.md.",
        "#",
        "# zero\tname",
        *(f"{zero:04X}\t{unicodedata.name(chr(zero), '?')}" for zero in zeros),
    ]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  systems={len(zeros)}  unicode={DATA_UNICODE_VERSION}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
