#!/usr/bin/env python3
"""Generate `tests/fixtures/ucd_script_ranges.tsv` — UCD `Script` for the curated scripts.

`detect_char_script` resolves a script by binary-searching a hand-curated table of
**block** ranges (`src/scripts.rs`). A block is not a script, and the difference shows up
in two ways that need to be told apart:

* the table **declines** to name a script for a code point whose UCD script it otherwise
  covers — 12,541 of them, mostly CJK and other extension blocks. That is the curated
  61-script scope doing its job, and it costs a caller a missed detection rather than a
  wrong answer.
* the table names a **different** script than the UCD does. That is wrong under any
  curation policy, and #819 found 33 — nineteen of which resolved to `Latin`, so a
  non-Latin letter beside ASCII read as single-script and `is_mixed_script` could not
  fire.

Nothing distinguished the two before this file existed. It is the independent data
`tests/test_script_table_agrees_with_ucd.py` checks the table against: without it the only
comparison available is the table against itself.

Scope: the scripts the table already names. Scripts outside the curated set are excluded,
because "we do not carry Tifinagh" is a scope statement and not a disagreement.

Regenerate with:

    python scripts/gen_ucd_script_ranges.py            # fetch from unicode.org
    python scripts/gen_ucd_script_ranges.py --file X   # from a local Scripts.txt
"""

from __future__ import annotations

import argparse
import pathlib
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "tests" / "fixtures" / "ucd_script_ranges.tsv"

#: The Unicode version this table is a snapshot of. Matches `assigned_ranges.tsv` and the
#: confusables data, so the crate has one Unicode story rather than three.
DATA_UNICODE_VERSION = "17.0.0"
SCRIPTS_URL = f"https://www.unicode.org/Public/{DATA_UNICODE_VERSION}/ucd/Scripts.txt"

#: Surrogates are not scalar values — a Rust `char` cannot hold one, so they never reach
#: `detect_char_script`. Excluding them keeps the fixture honest about what it describes.
SURROGATES = range(0xD800, 0xE000)


def parse_scripts(text: str) -> dict[int, str]:
    """`Scripts.txt` as a code-point → script name map."""
    out: dict[int, str] = {}
    for raw in text.splitlines():
        line = raw.split("#")[0].strip()
        if not line:
            continue
        span, script = (part.strip() for part in line.split(";"))
        if ".." in span:
            start, end = (int(part, 16) for part in span.split(".."))
        else:
            start = end = int(span, 16)
        for cp in range(start, end + 1):
            out[cp] = script
    return out


def curated_scripts() -> set[str]:
    """The scripts `src/scripts.rs` names, read from the source rather than duplicated."""
    source = (ROOT / "src" / "scripts.rs").read_text(encoding="utf-8")
    body = source[source.index("static SCRIPT_RANGES") :]
    body = body[: body.index("\n];")]
    return {
        line.rsplit('"', 2)[-2]
        for line in body.splitlines()
        if line.strip().startswith("(0x") and '"' in line
    }


def to_ranges(pairs: list[tuple[int, str]]) -> list[tuple[int, int, str]]:
    ranges: list[list[object]] = []
    for cp, script in pairs:
        if ranges and ranges[-1][2] == script and ranges[-1][1] == cp - 1:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp, script])
    return [(int(a), int(b), str(s)) for a, b, s in ranges]


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--file", type=pathlib.Path, help="a local Scripts.txt")
    args = parser.parse_args(argv)

    if args.file:
        text = args.file.read_text(encoding="utf-8")
    else:
        with urllib.request.urlopen(SCRIPTS_URL, timeout=60) as response:  # noqa: S310
            text = response.read().decode("utf-8")

    ucd = parse_scripts(text)
    curated = curated_scripts()
    pairs = [
        (cp, script)
        for cp, script in sorted(ucd.items())
        if script in curated and cp not in SURROGATES
    ]
    ranges = to_ranges(pairs)

    lines = [
        f"# UCD {DATA_UNICODE_VERSION} Scripts.txt, restricted to the scripts",
        "# src/scripts.rs curates. Generated by scripts/gen_ucd_script_ranges.py —",
        "# see docs/provenance.md. Do not hand-edit.",
        "#",
        "# start\tend\tscript",
        *(f"{start:04X}\t{end:04X}\t{script}" for start, end, script in ranges),
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"wrote {OUT.relative_to(ROOT)}  ranges={len(ranges)}  "
        f"scripts={len(curated)}  unicode={DATA_UNICODE_VERSION}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
