#!/usr/bin/env python3
"""Generate `src/tables/data/bidi_strong_ranges.tsv` — UAX #9 strong direction.

`strong_dir` used to resolve a character's bidi direction by looking its *script name* up
in a five-element list (`RTL_SCRIPTS = ["Hebrew", "Arabic", "Syriac", "Thaana", "NKo"]`).
UAX #9 resolves direction from `Bidi_Class`, and the two are not the same question: 1,786
of the 3,018 assigned code points with `Bidi_Class` in {R, AL} resolved to no script at
all, so they were bidi-neutral to disarm while reordering normally on screen (#773).

Emits one row per range: `start`, `end`, `class`, where class is `L` (strong
left-to-right) or `R` (strong right-to-left, covering both `R` and `AL`). Everything else
— `EN`, `AN`, `WS`, the neutrals, the explicit formatting controls — is absent, which is
the same answer `strong_dir` gives them: no strong direction of their own.

Regenerate with:

    uv run --python 3.15 python scripts/gen_bidi_ranges.py
"""

from __future__ import annotations

import pathlib
import sys
import unicodedata

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "tables" / "data" / "bidi_strong_ranges.tsv"

#: Matches the other bundled Unicode snapshots so the crate has one Unicode story.
DATA_UNICODE_VERSION = "17.0.0"

SURROGATES = range(0xD800, 0xE000)


def strong_class(cp: int) -> str | None:
    """`"L"`, `"R"`, or `None` for a character with no strong direction."""
    if cp in SURROGATES:
        return None
    bc = unicodedata.bidirectional(chr(cp))
    if bc == "L":
        return "L"
    if bc in ("R", "AL"):
        return "R"
    return None


def main() -> None:
    if unicodedata.unidata_version != DATA_UNICODE_VERSION:
        sys.exit(
            f"gen_bidi_ranges must run under a UCD matching the declared data version "
            f"({DATA_UNICODE_VERSION}); this Python ships "
            f"{unicodedata.unidata_version}."
        )

    rows: list[tuple[int, int, str]] = []
    start: int | None = None
    current: str | None = None
    for cp in range(0x110000):
        cls = strong_class(cp)
        if cls != current:
            if current is not None and start is not None:
                rows.append((start, cp - 1, current))
            start, current = (cp, cls) if cls is not None else (None, None)
    if current is not None and start is not None:
        rows.append((start, 0x10FFFF, current))

    header = [
        "# UAX #9 strong bidi direction (start\tend\tclass, inclusive, hex).",
        "#",
        "# `L` = Bidi_Class L. `R` = Bidi_Class R or AL. Everything else is absent:",
        "# EN/AN digits, whitespace, the neutrals and the explicit formatting controls",
        "# have no strong direction of their own, which is what `strong_dir` returns for",
        "# a code point this table does not cover.",
        "#",
        "# `strong_dir` previously resolved direction from a five-name script list, so",
        "# 1,786 of 3,018 assigned R/AL code points were bidi-neutral to disarm while",
        "# reordering normally on screen (#773).",
        "#",
        f"# Unicode {unicodedata.unidata_version}, generated by CPython {sys.version.split()[0]}.",
        "# Regenerate: uv run --python 3.15 python scripts/gen_bidi_ranges.py",
    ]
    body = [f"{s:04X}\t{e:04X}\t{c}" for s, e, c in rows]
    OUT.write_text("\n".join(header + body) + "\n", encoding="utf-8")
    ltr = sum(e - s + 1 for s, e, c in rows if c == "L")
    rtl = sum(e - s + 1 for s, e, c in rows if c == "R")
    print(f"  → bidi strong ranges: {len(rows)} rows ({ltr} L, {rtl} R) → {OUT.name}")


if __name__ == "__main__":
    main()
