#!/usr/bin/env python3
"""Generate `src/tables/data/word_joiners.tsv` — the within-word joiner code points.

`seg_word` recognises single-letter segmentation: `v.i.a.g.r.a` is a finding because the
separators sit inside one token. It recognised exactly three separator characters — `.`,
`_` and `-` — while Unicode has two whole general categories for joining parts of one
word: `Pd` (dash punctuation) and `Pc` (connector punctuation).

Measured over the fully-atomized token `c<SEP>o<SEP>n<SEP>f<SEP>i<SEP>r<SEP>m`, the exact
shape the branch is documented to catch, 16 of the 36 joiners #750 enumerated were silent
on every path. That census was taken against an older UCD; this generator derives the set
rather than restating it, so the count here is whatever `DATA_UNICODE_VERSION` says (38 at
17.0.0, which has one more `Pd` than the issue counted).
Two of them — `U+2E40` and `U+30A0` — are the sharp case: `canonicalize` actively
rewrites them to `=`, which was not in the recognised set either, so the fold moved the
attack from one unrecognised separator to another.

`U+2010 HYPHEN` and `U+002D HYPHEN-MINUS` render identically and disagreed: the branch
fired on `c-o-n-f-i-r-m` and reported `c‐o‐n‐f‐i‐r‐m` clean.

Derived from the general category rather than curated, so a Unicode release that adds a
dash cannot leave a hole. It is a snapshot of a Unicode version, so it carries the same
obligations as every other bundled table: a row in `docs/provenance.md` and drift gates in
`tests/test_word_joiners.py`. Regenerate with:

    uv run --python 3.15 python scripts/gen_word_joiners.py
"""

from __future__ import annotations

import pathlib
import sys
import unicodedata

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "tables" / "data" / "word_joiners.tsv"

#: The Unicode version this table is a snapshot of. Matches the confusables data and
#: `assigned_ranges.tsv`, so the crate has one Unicode story rather than several.
DATA_UNICODE_VERSION = "17.0.0"

#: `Pd` is dash punctuation, `Pc` is connector punctuation. Both categories exist to join
#: parts of one word, which is precisely the shape `seg_word` looks for. No other category
#: qualifies wholesale: `Po` holds `.` and `!` alike, so the full stop is listed by hand
#: below rather than by pulling in every other punctuation mark with it.
JOINER_CATEGORIES = ("Pd", "Pc")

#: `U+002E FULL STOP` is `Po` and is the separator the branch was built for
#: (`v.i.a.g.r.a`), so it is kept explicitly rather than by widening the category test to
#: a class that also contains `?`, `!` and `@`.
EXTRA = (0x002E,)


def joiners() -> list[int]:
    """Every code point whose general category is a within-word joiner, plus `EXTRA`."""
    found = [
        cp
        for cp in range(0x110000)
        if not (0xD800 <= cp < 0xE000) and unicodedata.category(chr(cp)) in JOINER_CATEGORIES
    ]
    return sorted(set(found) | set(EXTRA))


def main() -> None:
    if unicodedata.unidata_version != DATA_UNICODE_VERSION:
        sys.exit(
            f"gen_word_joiners must run under a UCD matching the declared data version "
            f"({DATA_UNICODE_VERSION}); this Python ships "
            f"{unicodedata.unidata_version}. Anything else writes a table that claims a "
            f"version it was not built from."
        )

    cps = joiners()
    by_cat: dict[str, int] = {}
    for cp in cps:
        cat = unicodedata.category(chr(cp))
        by_cat[cat] = by_cat.get(cat, 0) + 1
    census = ", ".join(f"{n} {cat}" for cat, n in sorted(by_cat.items()))
    header = [
        "# Within-word joiner code points (hex, one per line).",
        "#",
        "# The separator set for `seg_word`, which detects single-letter segmentation",
        "# (`v.i.a.g.r.a`). It recognised three characters — . _ - — while Unicode has a",
        "# whole category for joining parts of one word. #750 measured 16 of them silent",
        "# on every path, and U+2010 HYPHEN disagreeing with U+002D HYPHEN-MINUS while",
        "# rendering identically.",
        "#",
        f"# This snapshot: {len(cps)} code points ({census}).",
        "#",
        "# Derived from the general category, not curated, so a Unicode release that adds",
        "# a dash cannot leave a hole. U+002E FULL STOP is added explicitly: it is Po, and",
        "# widening the test to Po would pull in ? ! @ and every other punctuation mark.",
        "#",
        f"# Unicode {unicodedata.unidata_version}, generated by CPython {sys.version.split()[0]}.",
        "# Regenerate: uv run --python 3.15 python scripts/gen_word_joiners.py",
    ]
    body = [f"{cp:04X}" for cp in cps]
    OUT.write_text("\n".join(header + body) + "\n", encoding="utf-8")
    print(f"  → word joiners: {len(cps)} code points ({census}) → {OUT.name}")


if __name__ == "__main__":
    main()
