#!/usr/bin/env python3
"""Generate `src/tables/data/assigned_ranges.tsv` — the assigned code point spans.

`detect_char_script` resolves a script by binary-searching a hand-curated table of
**block** ranges (`src/scripts.rs`). Blocks are not scripts, and a block contains holes:
`U+05EB` is an unassigned hole in the Hebrew block, `U+FDD0` is a noncharacter inside
Arabic Presentation Forms-A. Both inherited the surrounding block's script, so a code
point that does not exist reported as Hebrew or Arabic — and `"hello" + U+FDD0` came back
as `bidi_mixed` (#774).

This file is the assigned-ness gate. `detect_char_script` consults it first and declines
to name a script for anything unassigned, which closes the holes without disturbing the
curated 61-script scope the block table deliberately encodes.

It is a snapshot of a Unicode version, so it carries the same obligations as every other
bundled table: a row in `docs/provenance.md` and drift gates in
`tests/test_assigned_ranges.py`. Regenerate with:

    uv run --python 3.15 python scripts/gen_assigned_ranges.py
"""

from __future__ import annotations

import pathlib
import sys
import unicodedata

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "tables" / "data" / "assigned_ranges.tsv"

#: The Unicode version this table is a snapshot of. Matches the confusables data so the
#: crate has one Unicode story rather than two.
DATA_UNICODE_VERSION = "17.0.0"

#: Surrogates are not scalar values. Rust `char` cannot hold one, so they can never reach
#: `detect_char_script`; excluding them keeps the table honest about what it describes.
SURROGATES = range(0xD800, 0xE000)


def assigned_ranges() -> list[tuple[int, int]]:
    """Contiguous spans of assigned code points, surrogates excluded."""
    spans: list[tuple[int, int]] = []
    start: int | None = None
    for cp in range(0x110000):
        assigned = cp not in SURROGATES and unicodedata.category(chr(cp)) != "Cn"
        if assigned and start is None:
            start = cp
        elif not assigned and start is not None:
            spans.append((start, cp - 1))
            start = None
    if start is not None:
        spans.append((start, 0x10FFFF))
    return spans


def main() -> None:
    if unicodedata.unidata_version != DATA_UNICODE_VERSION:
        sys.exit(
            f"gen_assigned_ranges must run under a UCD matching the declared data "
            f"version ({DATA_UNICODE_VERSION}); this Python ships "
            f"{unicodedata.unidata_version}. Anything else writes a table that claims a "
            f"version it was not built from."
        )

    spans = assigned_ranges()
    header = [
        "# Assigned code point ranges (start\tend, inclusive, hex).",
        "#",
        "# `detect_char_script` resolves scripts from a hand-curated table of *block*",
        "# ranges, and a block has holes: U+05EB is unassigned inside the Hebrew block,",
        "# U+FDD0 is a noncharacter inside Arabic Presentation Forms-A. Both inherited the",
        "# surrounding block's script (#774). This table is the gate that stops a code",
        "# point which does not exist from being given a script.",
        "#",
        "# Surrogates are excluded: Rust `char` cannot hold one, so they never reach the",
        "# lookup, and listing them would describe a case that cannot occur.",
        "#",
        f"# Unicode {unicodedata.unidata_version}, generated by CPython {sys.version.split()[0]}.",
        "# Regenerate: uv run --python 3.15 python scripts/gen_assigned_ranges.py",
    ]
    body = [f"{s:04X}\t{e:04X}" for s, e in spans]
    OUT.write_text("\n".join(header + body) + "\n", encoding="utf-8")
    covered = sum(e - s + 1 for s, e in spans)
    print(f"  → assigned ranges: {len(spans)} spans, {covered} code points → {OUT.name}")


if __name__ == "__main__":
    main()
