/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_DISARM_CABI__
#define __RUST_DISARM_CABI__
#ifdef __cplusplus
extern "C" {
#endif

/** \brief
 *  Full hostname homoglyph analysis as a JSON object (fields mirror the Rust/Node/
 *  Ruby/Java `HostnameAnalysis`: `suspicious`, `scripts`, `mixed_script`,
 *  `has_confusables`, `bidi_conflict`, `bidi_control`, `has_invisible`, `cross_label_script`, `label_scripts`,
 *  `whole_script_confusable`, `label_whole_script_confusable`, `canonical`).
 */
char *
disarm_analyze_hostname (
    char const * host);


#include <stdbool.h>

/** \brief
 *  [`disarm_analyze_hostname`] with the opt-in digraph contraction pass (#562).
 *
 *  `contractions = true` additionally folds the ASCII digraphs (`rn`→`m`, `vv`→`w`,
 *  `cl`→`d`) per label, so `arnazon.com` canonicalizes to `amazon.com`. It changes
 *  `canonical` only — the `suspicious` verdict is unaffected, because an all-ASCII label
 *  carries no mixed-script or cross-script evidence. Compare `canonical` against your own
 *  brand list.
 *
 *  Separate entry point rather than a widened `disarm_analyze_hostname`: that symbol
 *  shipped in 0.13.0 and callers are linked against its 1-argument form. Same shape as
 *  `disarm_transliterate` / `_opts` and `disarm_normalize_confusables` / `_opts`.
 */
char *
disarm_analyze_hostname_opts (
    char const * host,
    bool contractions);

/** \brief
 *  Result of a fallible transform: exactly one of `value` / `error` is non-NULL.
 *  The caller frees whichever is set with [`disarm_string_free`].
 */
typedef struct DisarmResult {
    /** \brief
     *  The output string, or NULL on error.
     */
    char * value;

    /** \brief
     *  The error message, or NULL on success.
     */
    char * error;
} DisarmResult_t;

/** \brief
 *  The strongest security-canonicalization preset.
 */
DisarmResult_t
disarm_canonicalize (
    char const * text);

/** \brief
 *  Library-catalog dedup key; `lang` may be NULL, `strict_iso9` selects ISO 9:1995.
 */
DisarmResult_t
disarm_catalog_key (
    char const * text,
    char const * lang,
    bool strict_iso9);

/** \brief
 *  Collapse runs of whitespace to single spaces and trim.
 */
char *
disarm_collapse_whitespace (
    char const * text);

/** \brief
 *  The Unicode `confusables.txt` release the bundled confusable tables were folded
 *  from, e.g. `"17.0.0"` (#560). Free the result with [`disarm_string_free`].
 *
 *  Not a Unicode version for the library as a whole: disarm's case-folding and width
 *  tables track different releases (see `docs/provenance.md`). This answers one
 *  question — how current is the confusables fold?
 */
char *
disarm_confusables_version (void);

/** \brief
 *  Replace emoji with their plain names; `strip_modifiers` drops skin-tone marks.
 */
char *
disarm_demojize (
    char const * text,
    bool strip_modifiers);

/** \brief
 *  Confusable sources in `text` the bundled `target` table does not fold, as a JSON
 *  array of `{"char": "…", "offset": N}` objects in order of appearance — the
 *  confusables analogue of `find_untranslatable`, with the same byte-offset
 *  convention. Free with [`disarm_string_free`].
 */
DisarmResult_t
disarm_find_unmapped_confusables (
    char const * text,
    char const * target);

/** \brief
 *  Unicode case folding (aggressive lowercase for caseless comparison).
 */
char *
disarm_fold_case (
    char const * text);


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  Number of grapheme clusters (user-perceived characters) in `text`.
 */
uint64_t
disarm_grapheme_len (
    char const * text);

/** \brief
 *  Whether `text` mixes strong LTR and strong RTL characters ("BiDi Swap").
 */
bool
disarm_has_bidi_conflict (
    char const * text);

/** \brief
 *  Structural anomaly report for `text` as a JSON object (`anomalous`, `kinds`,
 *  `findings` [each `kind`/`token`/`start`/`end`/`detail`/`reason`], `reason`).
 *
 *  `lexicon_json` is a JSON array of common words (e.g. `["free","account"]`),
 *  mirroring the array form the Node/Ruby bindings accept — it feeds the
 *  word-list branches (`leet`, `segmentation`). An empty string, `"[]"`, `"null"`,
 *  or malformed JSON means "no lexicon": the structural branches (invisible, bidi,
 *  zalgo, mixed-script) still fire, matching the other bindings' no-arg behaviour.
 */
char *
disarm_inspect_anomalies (
    char const * text,
    char const * lexicon_json);

/** \brief
 *  Auto-language inspection for `text` as a JSON object (`script`, `chosen_lang`,
 *  `reason`, `discriminators_hit`).
 */
char *
disarm_inspect_auto_lang (
    char const * text);

/** \brief
 *  Whether `text` mixes characters from more than one script.
 */
bool
disarm_is_mixed_script (
    char const * text);

/** \brief
 *  Whether the hostname looks like a mixed-script / confusable / bidi IDN spoof.
 */
bool
disarm_is_suspicious_hostname (
    char const * host);

/** \brief
 *  Metadata for a language code as JSON (`name`, `script`, `region`, `context`), or
 *  an error in the [`DisarmResult`] for an unknown code.
 */
DisarmResult_t
disarm_lang_info (
    char const * code);

/** \brief
 *  ML/NLP normalization: NFKC → emoji→text → transliterate → strip accents →
 *  [case fold] → strip control → strip zero-width → collapse whitespace.
 *
 *  `lang` is nullable (NULL = no transliteration). `emoji_style` is `"cldr"` or
 *  `"none"`. `fold_case` drops the case-fold step when false — pass false in front of a
 *  CASED model; it restores case, not diacritics. Folds no confusables, so it is not a
 *  homoglyph defence at any setting.
 */
DisarmResult_t
disarm_ml_normalize (
    char const * text,
    char const * lang,
    char const * emoji_style,
    bool fold_case);

/** \brief
 *  Apply a normalization form: `"NFC"` | `"NFD"` | `"NFKC"` | `"NFKD"`.
 */
DisarmResult_t
disarm_normalize (
    char const * text,
    char const * form);

/** \brief
 *  Fold cross-script confusables toward `target` (`"latin"` | `"cyrillic"`).
 */
DisarmResult_t
disarm_normalize_confusables (
    char const * text,
    char const * target);

/** \brief
 *  [`disarm_normalize_confusables`] with an explicit `digit_policy` (#561).
 *
 *  `digit_policy` is `"numeric"` (disarm's reading: a non-Latin digit folds to the ASCII
 *  digit) or `"tr39"` (upstream's, which folds most of them to a Latin letter; three of
 *  the 45 rows are not — two fold to `.` and one to the two characters `rn`). `"tr39"` is
 *  scoped to `target = "latin"`: the override rows are generated from the Latin table and
 *  carry TR39's Latin-script targets, so with any other target it is a no-op. Added as an
 *  `_opts` variant rather than by widening the existing entry point, so the two-argument
 *  symbol keeps its ABI for callers already linked against it — the same shape
 *  `disarm_transliterate` / `disarm_transliterate_opts` already use in this file.
 */
DisarmResult_t
disarm_normalize_confusables_opts (
    char const * text,
    char const * target,
    char const * digit_policy);

/** \brief
 *  Reverse-transliterate Latin → native script. `lang` is `"el"` | `"ru"` | `"uk"`.
 */
DisarmResult_t
disarm_reverse_transliterate (
    char const * text,
    char const * lang);

/** \brief
 *  Metadata for a script name as JSON (`name`, `default_lang`, `example`,
 *  `context_aware`), or an error in the [`DisarmResult`] for an unknown name.
 */
DisarmResult_t
disarm_script_info (
    char const * name);

/** \brief
 *  Case/accent/script-insensitive search key; `lang` may be NULL.
 */
DisarmResult_t
disarm_search_key (
    char const * text,
    char const * lang);

/** \brief
 *  Collation sort key (preserves base accented characters); `lang` may be NULL.
 */
DisarmResult_t
disarm_sort_key (
    char const * text,
    char const * lang);

/** \brief
 *  Free a string previously returned by any `disarm_*` function. NULL-safe: the
 *  argument is a nullable owned box, so passing NULL (e.g. the unused half of a
 *  [`DisarmResult`]) is a no-op; a non-NULL box is dropped, freeing it.
 */
void
disarm_string_free (
    char * string);

/** \brief
 *  Strip diacritics, leaving base letters.
 */
char *
disarm_strip_accents (
    char const * text);

/** \brief
 *  Remove bidi control characters.
 */
char *
disarm_strip_bidi (
    char const * text);

/** \brief
 *  Remove control characters.
 */
char *
disarm_strip_control_chars (
    char const * text);

/** \brief
 *  Strip every Unicode noncharacter.
 */
char *
disarm_strip_noncharacters (
    char const * text);

/** \brief
 *  Aggressively strip obfuscation (invisibles, bidi, zero-width, etc.).
 */
DisarmResult_t
disarm_strip_obfuscation (
    char const * text);

/** \brief
 *  Strip every Private Use Area code point.
 */
char *
disarm_strip_pua (
    char const * text);

/** \brief
 *  Strip the Unicode Tags block (U+E0000–U+E007F), preserving valid emoji flags.
 */
char *
disarm_strip_tags (
    char const * text);

/** \brief
 *  Strip every variation selector (VS1–VS256).
 */
char *
disarm_strip_variation_selectors (
    char const * text);

/** \brief
 *  Remove zero-width characters.
 */
char *
disarm_strip_zero_width_chars (
    char const * text);

/** \brief
 *  Total terminal display width of `text` (`ambiguous_wide` treats ambiguous
 *  East-Asian width characters as wide).
 */
uint64_t
disarm_terminal_width (
    char const * text,
    bool ambiguous_wide);

/** \brief
 *  Unicode → ASCII with the default scheme.
 */
char *
disarm_transliterate (
    char const * text);

/** \brief
 *  Transliterate with a scheme (`"default"` | `"strict_iso9"` | `"gost7034"`) and an
 *  optional language profile (`lang` may be NULL).
 */
DisarmResult_t
disarm_transliterate_opts (
    char const * text,
    char const * scheme,
    char const * lang);

/** \brief
 *  Every upstream confusable source the bundled `target` table does not fold, as a
 *  JSON array of single-character strings. Free with [`disarm_string_free`].
 *
 *  Read as exposure, not as a score. The set includes five ASCII characters
 *  (`%`, `0`, `1`, `I`, `m`): TR39 is a skeleton transform, and disarm deliberately
 *  does not apply those rows because folding a legitimate `m` to `rn` corrupts prose.
 */
DisarmResult_t
disarm_unmapped_confusables (
    char const * target);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_DISARM_CABI__ */
