/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_DISARM_CABI__
#define __RUST_DISARM_CABI__
#ifdef __cplusplus
extern "C" {
#endif

/** \brief
 *  Full hostname homoglyph analysis as a JSON object (fields mirror the Rust/Node/
 *  Ruby/Java `HostnameAnalysis`: `suspicious`, `scripts`, `mixed_script`,
 *  `has_confusables`, `bidi_conflict`, `bidi_control`, `has_invisible`, `compat_fold`,
 *  `cross_label_script`, `label_scripts`, `whole_script_confusable`,
 *  `label_whole_script_confusable`, `canonical`).
 */
char *
disarm_analyze_hostname (
    char const * host);


#include <stdbool.h>

/** \brief
 *  [`disarm_analyze_hostname`] with the opt-in digraph contraction pass (#562).
 *
 *  `contractions = true` additionally folds the ASCII digraphs (`rn`→`m`, `vv`→`w`,
 *  `cl`→`d`) per label, so `arnazon.com` canonicalizes to `amazon.com`. It changes
 *  `canonical` only — the `suspicious` verdict is unaffected, because an all-ASCII label
 *  carries no mixed-script or cross-script evidence. Compare `canonical` against your own
 *  brand list.
 *
 *  Separate entry point rather than a widened `disarm_analyze_hostname`: that symbol
 *  shipped in 0.13.0 and callers are linked against its 1-argument form. Same shape as
 *  `disarm_transliterate` / `_opts` and `disarm_normalize_confusables` / `_opts`.
 */
char *
disarm_analyze_hostname_opts (
    char const * host,
    bool contractions);

/** \brief
 *  Result of a fallible transform: exactly one of `value` / `error` is non-NULL.
 *  The caller frees whichever is set with [`disarm_string_free`].
 */
typedef struct DisarmResult {
    /** \brief
     *  The output string, or NULL on error.
     */
    char * value;

    /** \brief
     *  The error message, or NULL on success.
     */
    char * error;
} DisarmResult_t;

/** \brief
 *  The strongest security-canonicalization preset.
 *
 *  Two steps introduce ASCII, not one (#719): the leading NFKC, and the confusable fold,
 *  which reaches characters NFKC leaves alone. `U+2236 RATIO` becomes `:`, `U+2044
 *  FRACTION SLASH` becomes `/`, `U+2216 SET MINUS` becomes `\`. A string that carried no
 *  delimiter can leave here carrying one. `disarm_inspect_anomalies` reports it as
 *  `confusable` WHEN the word also carries an ASCII letter, which is the gate that keeps
 *  ordinary non-Latin text from firing; a delimiter-only string is not reported.
 */
DisarmResult_t
disarm_canonicalize (
    char const * text);

/** \brief
 *  `disarm_canonicalize` under a `digit_policy` (#896): `"numeric"` — the default, and
 *  byte-identical to the one-argument form — `"tr39"` or `"preserve"`. An `_opts` symbol
 *  rather than a widened one, so the existing entry point keeps its ABI for callers already
 *  linked against it — the shape `disarm_normalize_confusables_opts` uses.
 */
DisarmResult_t
disarm_canonicalize_opts (
    char const * text,
    char const * digit_policy);

/** \brief
 *  Canonicalize, but fail rather than silently normalize a structural difference away.
 *
 *  The half of the pair that lets a caller *reject* input instead of comparing a value
 *  the sender never wrote.
 */
DisarmResult_t
disarm_canonicalize_strict (
    char const * text);

/** \brief
 *  `disarm_canonicalize_strict` under a `digit_policy` (#896). See `disarm_canonicalize_opts`.
 */
DisarmResult_t
disarm_canonicalize_strict_opts (
    char const * text,
    char const * digit_policy);

/** \brief
 *  Library-catalog dedup key; `lang` may be NULL, `strict_iso9` selects ISO 9:1995.
 */
DisarmResult_t
disarm_catalog_key (
    char const * text,
    char const * lang,
    bool strict_iso9);

/** \brief
 *  `disarm_catalog_key` under a `digit_policy` (#896); `lang` may be NULL.
 */
DisarmResult_t
disarm_catalog_key_opts (
    char const * text,
    char const * lang,
    bool strict_iso9,
    char const * digit_policy);

/** \brief
 *  Collapse runs of whitespace to single spaces and trim.
 */
char *
disarm_collapse_whitespace (
    char const * text);

/** \brief
 *  Per-script confusable coverage as JSON (`script`, `sources`, `folded`), or an error
 *  in the [`DisarmResult`] for an unknown script (#963).
 *
 *  The denominator [`disarm_unmapped_confusables`] does not have: that measures one
 *  bundled table against the whole 6,565-source population, so a script disarm ships no
 *  table for reports a number determined by that absence rather than by its coverage.
 *  `folded` counts sources any bundled table reaches, not sources folded *toward* this
 *  script.
 */
DisarmResult_t
disarm_confusable_coverage (
    char const * script);

/** \brief
 *  The Unicode `confusables.txt` release the bundled confusable tables were folded
 *  from, e.g. `"17.0.0"` (#560). Free the result with [`disarm_string_free`].
 *
 *  Not a Unicode version for the library as a whole: disarm's case-folding and width
 *  tables track different releases (see `docs/provenance.md`). This answers one
 *  question — how current is the confusables fold?
 */
char *
disarm_confusables_version (void);

/** \brief
 *  Replace emoji with their plain names; `strip_modifiers` drops skin-tone marks.
 */
char *
disarm_demojize (
    char const * text,
    bool strip_modifiers);


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  Levenshtein edit distance between `a` and `b`, in characters (#894). The one class of
 *  registry spoofing the confusable tables deliberately do not model: `paypa1`, `adm1n`.
 */
size_t
disarm_edit_distance (
    char const * a,
    char const * b);

/** \brief
 *  Which of `values_json` are the same name under `key` (#620), as a JSON array of
 *  objects (`key`, `values`, `indices`).
 *
 *  `values_json` is a JSON array of strings — the set to check. `key` names the
 *  reducer: `"fold_case"`, `"search_key"`, `"catalog_key"`, `"canonicalize"`,
 *  `"canonicalize_strict"` or `"normalize_confusables"`. There is no default,
 *  because a stronger key finds more collisions and the choice is the caller's
 *  policy. `lang` may be NULL and reaches `search_key` / `catalog_key` only.
 *
 *  A group is reported only when two or more **distinct** inputs share a key.
 *  Malformed `values_json` is an error rather than an empty set, so a caller
 *  cannot read a parse failure as "no collisions".
 */
DisarmResult_t
disarm_find_key_collisions (
    char const * values_json,
    char const * key,
    char const * lang);

/** \brief
 *  Confusable sources in `text` the bundled `target` table does not fold, as a JSON
 *  array of `{"char": "…", "offset": N}` objects in order of appearance — the
 *  confusables analogue of `find_untranslatable`, with the same byte-offset
 *  convention. Free with [`disarm_string_free`].
 */
DisarmResult_t
disarm_find_unmapped_confusables (
    char const * text,
    char const * target);

/** \brief
 *  Unicode case folding (aggressive lowercase for caseless comparison).
 */
char *
disarm_fold_case (
    char const * text);

/** \brief
 *  Number of grapheme clusters (user-perceived characters) in `text`.
 */
uint64_t
disarm_grapheme_len (
    char const * text);

/** \brief
 *  Whether `text` mixes strong LTR and strong RTL characters ("BiDi Swap").
 */
bool
disarm_has_bidi_conflict (
    char const * text);

/** \brief
 *  All twelve UAX #9 explicit formatting characters, uncontexted (#778).
 *  The counterpart to `has_bidi_conflict`, which reads strong-direction letters and is
 *  blind to these; the two are disjoint. The anomaly detector's `bidi` kind reports nine
 *  of the twelve, holding back LRM, RLM and ALM because a lone directional mark is
 *  ordinary in right-to-left text.
 */
bool
disarm_has_bidi_control (
    char const * text);

/** \brief
 *  Structural anomaly report for `text` as a JSON object (`anomalous`, `kinds`,
 *  `findings` [each `kind`/`token`/`start`/`end`/`detail`/`reason`], `reason`).
 *
 *  `lexicon_json` is a JSON array of common words (e.g. `["free","account"]`),
 *  mirroring the array form the Node/Ruby bindings accept — it feeds the
 *  word-list branches (`leet`, `segmentation`). An empty string, `"[]"`, `"null"`,
 *  or malformed JSON means "no lexicon": the structural branches (invisible, bidi,
 *  zalgo, mixed-script) still fire, matching the other bindings' no-arg behaviour.
 */
char *
disarm_inspect_anomalies (
    char const * text,
    char const * lexicon_json);

/** \brief
 *  Auto-language inspection for `text` as a JSON object (`script`, `chosen_lang`,
 *  `reason`, `discriminators_hit`).
 */
char *
disarm_inspect_auto_lang (
    char const * text);

/** \brief
 *  Whether `text` is already its own canonical form under `preset` (#730).
 *
 *  Returns `1` for canonical, `0` for not, and `-1` when `preset` names neither a preset
 *  nor a profile. A tri-state rather than a `bool`, because every other predicate here is
 *  infallible and this one takes a name that can be wrong — answering `0` for an unknown
 *  preset would report "not canonical" for a question that was never asked.
 */
int8_t
disarm_is_canonical (
    char const * text,
    char const * preset);

/** \brief
 *  Whether case folding and simple lowercasing agree, so `text` is a stable
 *  identity key ("groß.txt" is not; "gross.txt" is).
 */
bool
disarm_is_case_fold_stable (
    char const * text);

/** \brief
 *  Whether `text` mixes characters from more than one script.
 */
bool
disarm_is_mixed_script (
    char const * text);

/** \brief
 *  Whether the hostname looks like a mixed-script / confusable / bidi IDN spoof.
 */
bool
disarm_is_suspicious_hostname (
    char const * host);

/** \brief
 *  Whether a key stored under an earlier release still compares equal (#645).
 *
 *  A monotonic counter, not a version: two artifacts reporting the same value produce the
 *  same key for the same input, and different values mean reindex. Meaningless in
 *  isolation, by design — the question a key consumer has is a comparison, not a lookup.
 */
uint32_t
disarm_key_schema_version (void);

/** \brief
 *  Metadata for a language code as JSON (`name`, `script`, `region`, `context`), or
 *  an error in the [`DisarmResult`] for an unknown code.
 */
DisarmResult_t
disarm_lang_info (
    char const * code);

/** \brief
 *  ML/NLP normalization: NFKC → emoji→text → transliterate → strip accents →
 *  [case fold] → strip control → strip zero-width → collapse whitespace.
 *
 *  `lang` is nullable (NULL = no transliteration). `emoji_style` is `"cldr"` or
 *  `"none"`. `fold_case` drops the case-fold step when false — pass false in front of a
 *  CASED model; it restores case, not diacritics. Folds no confusables, so it is not a
 *  homoglyph defence at any setting.
 */
DisarmResult_t
disarm_ml_normalize (
    char const * text,
    char const * lang,
    char const * emoji_style,
    bool fold_case);

/** \brief
 *  The candidate closest to `value`, or `null` beyond `max_distance` (#894).
 *
 *  `candidates_json` is a JSON array of strings; the result is the JSON object
 *  `{"value": "...", "distance": n}` or the JSON literal `null` — the same transport the
 *  structured reports use. Malformed `candidates_json` is an error rather than `null`, so
 *  a caller cannot read a parse failure as "nothing close". An exact match is reported
 *  with distance 0; ties go to the first candidate at the lowest distance.
 */
DisarmResult_t
disarm_nearest_match (
    char const * value,
    char const * candidates_json,
    size_t max_distance);

/** \brief
 *  Apply a normalization form: `"NFC"` | `"NFD"` | `"NFKC"` | `"NFKD"`.
 */
DisarmResult_t
disarm_normalize (
    char const * text,
    char const * form);

/** \brief
 *  Fold cross-script confusables toward `target` (`"latin"` | `"cyrillic"` | `"arabic"` | `"hebrew"`).
 */
DisarmResult_t
disarm_normalize_confusables (
    char const * text,
    char const * target);

/** \brief
 *  [`disarm_normalize_confusables`] with an explicit `digit_policy` (#561).
 *
 *  `digit_policy` is `"numeric"` (disarm's reading: a non-Latin digit folds to the ASCII
 *  digit) or `"tr39"` (upstream's, which folds most of them to a Latin letter; three of
 *  the 45 rows are not — two fold to `.` and one to the two characters `rn`). `"tr39"` is
 *  scoped to `target = "latin"`: the override rows are generated from the Latin table and
 *  carry TR39's Latin-script targets, so with any other target it is a no-op.
 *  `"preserve"` leaves the digit alone (#648); the other two both produce a mixed-script
 *  numeral, and it applies under every target script. Added as an
 *  `_opts` variant rather than by widening the existing entry point, so the two-argument
 *  symbol keeps its ABI for callers already linked against it — the same shape
 *  `disarm_transliterate` / `disarm_transliterate_opts` already use in this file.
 */
DisarmResult_t
disarm_normalize_confusables_opts (
    char const * text,
    char const * target,
    char const * digit_policy);

/** \brief
 *  Replace every emoji with `replacement`, verbatim (#972). Free the result with
 *  [`disarm_string_free`].
 *
 *  The counterpart to [`disarm_demojize`], and a different question of a different
 *  table: naming reads CLDR, which annotates more than the emoji, and this reads the
 *  UCD's emoji properties, so `\u{00A9}` and `\u{2122}` stay put. `replacement` is
 *  inserted exactly as given — `""` closes an intra-word split and `" "` keeps two
 *  words apart, and no rule serves both.
 */
char *
disarm_replace_emoji (
    char const * text,
    char const * replacement);

/** \brief
 *  Reverse-transliterate Latin → native script. `lang` is `"el"` | `"ru"` | `"uk"`.
 */
DisarmResult_t
disarm_reverse_transliterate (
    char const * text,
    char const * lang);

/** \brief
 *  Sanitize `text` into a filename safe on `platform` (#707).
 *
 *  The only entry point disarm ships whose *whole* purpose is a filesystem sink, and the
 *  C ABI is the surface most likely to be feeding one. `platform` is `"universal"`,
 *  `"posix"` or `"windows"`; `lang` is nullable (NULL = no transliteration profile).
 *
 *  Transliteration is load-bearing here, not a convenience: 19 of the 53 vectors in the
 *  attacker battery are neutralized by the romanization step rather than by the denylist
 *  (#601), so a caller who reaches for `disarm_strip_obfuscation` and its own denylist
 *  instead does not get the same protection.
 */
DisarmResult_t
disarm_sanitize_filename (
    char const * text,
    char const * separator,
    size_t max_length,
    char const * platform,
    char const * lang,
    bool preserve_extension);

/** \brief
 *  Metadata for a script name as JSON (`name`, `default_lang`, `example`,
 *  `context_aware`), or an error in the [`DisarmResult`] for an unknown name.
 */
DisarmResult_t
disarm_script_info (
    char const * name);

/** \brief
 *  Case/accent/script-insensitive search key; `lang` may be NULL.
 */
DisarmResult_t
disarm_search_key (
    char const * text,
    char const * lang);

/** \brief
 *  `disarm_search_key` under a `digit_policy` (#896); `lang` may be NULL. The fold runs on
 *  the raw text, before transliteration consumes the non-Latin digit the policy reads.
 */
DisarmResult_t
disarm_search_key_opts (
    char const * text,
    char const * lang,
    char const * digit_policy);

/** \brief
 *  The TR39 identifier skeleton plus the two prototype classes disarm's table keeps apart
 *  (#650). A spoof key: its only job is to make confusable identifiers collide, and its
 *  output is never for display. `digit_policy` is `"numeric"` (the letter half only),
 *  `"tr39"` (adds `1 ≡ l` and `0 ≡ O`) or `"preserve"`.
 */
DisarmResult_t
disarm_skeleton_key (
    char const * text,
    char const * digit_policy);

/** \brief
 *  Collation sort key (preserves base accented characters); `lang` may be NULL.
 */
DisarmResult_t
disarm_sort_key (
    char const * text,
    char const * lang);

/** \brief
 *  `disarm_sort_key` under a `digit_policy` (#896); `lang` may be NULL.
 */
DisarmResult_t
disarm_sort_key_opts (
    char const * text,
    char const * lang,
    char const * digit_policy);

/** \brief
 *  Free a string previously returned by any `disarm_*` function. NULL-safe: the
 *  argument is a nullable owned box, so passing NULL (e.g. the unused half of a
 *  [`DisarmResult`]) is a no-op; a non-NULL box is dropped, freeing it.
 */
void
disarm_string_free (
    char * string);

/** \brief
 *  Strip diacritics, leaving base letters.
 */
char *
disarm_strip_accents (
    char const * text);

/** \brief
 *  Remove bidi control characters.
 */
char *
disarm_strip_bidi (
    char const * text);

/** \brief
 *  Remove control characters.
 */
char *
disarm_strip_control_chars (
    char const * text);

/** \brief
 *  Strip the non-interchange and invisible classes while KEEPING the script (#698).
 *
 *  The seven universal `strip*` primitives cannot be composed into this, and the
 *  difference runs in both directions. `strip_format` is *less* destructive where
 *  rendering matters — it preserves the Private Use Area for icon fonts and keeps the
 *  VS15/VS16 presentation selectors after a base (`RENDERING_STRIP`), both of which the
 *  naive chain deletes — and *more* destructive with whitespace, because it ends in
 *  `CollapseWs` and folds TAB/LF to a space where the primitives leave them. The policy
 *  itself is a private constant, so a caller on this binding could not express it at all.
 *
 *  Unlike `canonicalize` it does NOT fold confusables, so non-Latin text keeps its script
 *  — the point of the preset.
 *
 *  Infallible: returns the string directly rather than a `DisarmResult`.
 */
char *
disarm_strip_format (
    char const * text);

/** \brief
 *  Strip every Unicode noncharacter.
 */
char *
disarm_strip_noncharacters (
    char const * text);

/** \brief
 *  Aggressively strip obfuscation (invisibles, bidi, zero-width, etc.).
 */
DisarmResult_t
disarm_strip_obfuscation (
    char const * text);

/** \brief
 *  `disarm_strip_obfuscation` under a `digit_policy` (#896). See `disarm_canonicalize_opts`.
 */
DisarmResult_t
disarm_strip_obfuscation_opts (
    char const * text,
    char const * digit_policy);

/** \brief
 *  Strip every Private Use Area code point.
 */
char *
disarm_strip_pua (
    char const * text);

/** \brief
 *  Strip the Unicode Tags block (U+E0000–U+E007F), preserving valid emoji flags.
 */
char *
disarm_strip_tags (
    char const * text);

/** \brief
 *  Strip every variation selector (VS1–VS256).
 */
char *
disarm_strip_variation_selectors (
    char const * text);

/** \brief
 *  Remove zero-width characters.
 */
char *
disarm_strip_zero_width_chars (
    char const * text);

/** \brief
 *  Total terminal display width of `text` (`ambiguous_wide` treats ambiguous
 *  East-Asian width characters as wide).
 */
uint64_t
disarm_terminal_width (
    char const * text,
    bool ambiguous_wide);

/** \brief
 *  Unicode → ASCII with the default scheme.
 */
char *
disarm_transliterate (
    char const * text);

/** \brief
 *  Transliterate with a scheme (`"default"` | `"strict_iso9"` | `"gost7034"`) and an
 *  optional language profile (`lang` may be NULL).
 */
DisarmResult_t
disarm_transliterate_opts (
    char const * text,
    char const * scheme,
    char const * lang);

/** \brief
 *  The UCD release disarm's normalizer implements (#645). Free with
 *  [`disarm_string_free`].
 *
 *  Not a library-wide Unicode version — the bundled tables track different releases, and
 *  `docs/provenance.md` is the census. This is the one integrators ask about, because it
 *  decides whether disarm's normalization agrees with the host platform's.
 */
char *
disarm_unicode_version (void);

/** \brief
 *  Every upstream confusable source the bundled `target` table does not fold, as a
 *  JSON array of single-character strings. Free with [`disarm_string_free`].
 *
 *  Read as exposure, not as a score. The set includes five ASCII characters
 *  (`%`, `0`, `1`, `I`, `m`): TR39 is a skeleton transform, and disarm deliberately
 *  does not apply those rows because folding a legitimate `m` to `rn` corrupts prose.
 */
DisarmResult_t
disarm_unmapped_confusables (
    char const * target);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_DISARM_CABI__ */
